/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlinhasach.view;

import com.mycompany.quanlinhasach.model.CTHD;
import com.toedter.calendar.JDateChooser;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author NGUYEN MY NGAN
 */
public class BanHang extends javax.swing.JPanel {

    private List<CTHD> chiTietHoaDonList = new ArrayList<>();
    /**
     * Creates new form BanHang1
     */
    public BanHang() {
        initComponents();
    
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThuTien = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        header3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtThuTien = new javax.swing.JTextField();
        ThuTienThanhToan = new javax.swing.JButton();
        ThuTienHuyBtn = new javax.swing.JButton();
        NhapSoLuong = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        header4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        SoLuongLuuBtn = new javax.swing.JButton();
        SoLuongHuyBtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKhachHang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateNgayNhap = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        SachHoadonTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        ThanhToanBtn = new javax.swing.JButton();
        HuyBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblDaTra = new javax.swing.JLabel();
        lblConLai = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SachTable = new javax.swing.JTable();
        function = new javax.swing.JPanel();
        TimKiem = new javax.swing.JTextField();
        TongSach2 = new javax.swing.JLabel();
        XoaBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        body1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKhachHang1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dateNgayNhap1 = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        SachHoadonTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        ThanhToanBtn1 = new javax.swing.JButton();
        HuyBtn1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblDaTra1 = new javax.swing.JLabel();
        lblConLai1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtSDT1 = new javax.swing.JTextField();
        txtMaNhanVien1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SachTable1 = new javax.swing.JTable();
        function1 = new javax.swing.JPanel();
        TimKiem1 = new javax.swing.JTextField();
        TongSach3 = new javax.swing.JLabel();
        Xuat2 = new javax.swing.JButton();
        Xuat3 = new javax.swing.JButton();
        XoaBtn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        ThuTien.setMinimumSize(new java.awt.Dimension(380, 200));

        header3.setBackground(new java.awt.Color(132, 94, 194));
        header3.setPreferredSize(new java.awt.Dimension(954, 30));
        header3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("THU TIỀN");
        header3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Nhập số tiền khách trả:");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        jPanel9.add(txtThuTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, 347, 40));

        ThuTienThanhToan.setBackground(new java.awt.Color(0, 201, 167));
        ThuTienThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        ThuTienThanhToan.setText("Thanh toán");
        ThuTienThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThuTienThanhToanActionPerformed(evt);
            }
        });
        jPanel9.add(ThuTienThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 95, 31));

        ThuTienHuyBtn.setBackground(new java.awt.Color(0, 201, 167));
        ThuTienHuyBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThuTienHuyBtn.setText("Hủy");
        jPanel9.add(ThuTienHuyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 86, 31));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(header3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThuTienLayout = new javax.swing.GroupLayout(ThuTien.getContentPane());
        ThuTien.getContentPane().setLayout(ThuTienLayout);
        ThuTienLayout.setHorizontalGroup(
            ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ThuTienLayout.setVerticalGroup(
            ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NhapSoLuong.setMinimumSize(new java.awt.Dimension(380, 200));

        header4.setBackground(new java.awt.Color(132, 94, 194));
        header4.setPreferredSize(new java.awt.Dimension(954, 30));
        header4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Nhập số lượng");
        header4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Nhập số lượng sách:");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        jPanel11.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, 347, 40));

        SoLuongLuuBtn.setBackground(new java.awt.Color(0, 201, 167));
        SoLuongLuuBtn.setForeground(new java.awt.Color(255, 255, 255));
        SoLuongLuuBtn.setText("Lưu");
        SoLuongLuuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoLuongLuuBtnActionPerformed(evt);
            }
        });
        jPanel11.add(SoLuongLuuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 95, 31));

        SoLuongHuyBtn.setBackground(new java.awt.Color(0, 201, 167));
        SoLuongHuyBtn.setForeground(new java.awt.Color(255, 255, 255));
        SoLuongHuyBtn.setText("Hủy");
        jPanel11.add(SoLuongHuyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 86, 31));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(header4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NhapSoLuongLayout = new javax.swing.GroupLayout(NhapSoLuong.getContentPane());
        NhapSoLuong.getContentPane().setLayout(NhapSoLuongLayout);
        NhapSoLuongLayout.setHorizontalGroup(
            NhapSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NhapSoLuongLayout.setVerticalGroup(
            NhapSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setPreferredSize(new java.awt.Dimension(1080, 678));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 234, 255), 12, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(132, 94, 194));
        jLabel1.setText("HÓA ĐƠN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Ngày lập:");

        txtKhachHang.setPreferredSize(new java.awt.Dimension(211, 30));
        txtKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachHangActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("SĐT:");

        dateNgayNhap.setPreferredSize(new java.awt.Dimension(146, 33));

        SachHoadonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sách", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SachHoadonTable.setRowHeight(40);
        jScrollPane2.setViewportView(SachHoadonTable);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Tổng tiền:");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTongTien.setText("0");

        ThanhToanBtn.setBackground(new java.awt.Color(0, 201, 167));
        ThanhToanBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThanhToanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pay.png"))); // NOI18N
        ThanhToanBtn.setText("Thanh toán");
        ThanhToanBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        ThanhToanBtn.setPreferredSize(new java.awt.Dimension(112, 43));
        ThanhToanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThanhToanBtnActionPerformed(evt);
            }
        });

        HuyBtn.setBackground(new java.awt.Color(0, 201, 167));
        HuyBtn.setForeground(new java.awt.Color(255, 255, 255));
        HuyBtn.setText("Hủy");
        HuyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        HuyBtn.setPreferredSize(new java.awt.Dimension(112, 43));
        HuyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBtnActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Đã trả:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setText("Còn lại:");

        lblDaTra.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDaTra.setText("0");

        lblConLai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblConLai.setText("0");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setText("Khách hàng:");

        txtSDT.setPreferredSize(new java.awt.Dimension(211, 30));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtMaNhanVien.setPreferredSize(new java.awt.Dimension(211, 30));
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Mã nhân viên:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConLai))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(lblDaTra)))
                .addGap(25, 25, 25))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addGap(219, 219, 219)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(HuyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ThanhToanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTongTien))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDaTra)
                    .addComponent(jLabel18))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConLai)
                    .addComponent(jLabel19))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HuyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThanhToanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        SachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Sách", "NXB", "Năm XB", "Đơn giá", "Tồn kho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SachTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SachTable.setShowGrid(false);
        jScrollPane1.setViewportView(SachTable);

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, 610));

        function.setBackground(new java.awt.Color(255, 255, 255));
        function.setPreferredSize(new java.awt.Dimension(996, 44));
        function.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimKiem.setBackground(new java.awt.Color(251, 234, 255));
        TimKiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        TimKiem.setPreferredSize(new java.awt.Dimension(247, 43));
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });
        function.add(TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 260, 30));

        TongSach2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TongSach2.setText("Tìm kiếm sách");
        function.add(TongSach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 120, -1));

        XoaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        XoaBtn.setBorder(null);
        XoaBtn.setContentAreaFilled(false);
        XoaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });
        function.add(XoaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(132, 94, 194));
        jLabel3.setText("BÁN HÀNG");
        function.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        add(function, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body1.setBackground(new java.awt.Color(255, 255, 255));
        body1.setPreferredSize(new java.awt.Dimension(1080, 678));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 234, 255), 12, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(132, 94, 194));
        jLabel4.setText("HÓA ĐƠN");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Ngày lập:");

        txtKhachHang1.setPreferredSize(new java.awt.Dimension(211, 30));
        txtKhachHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachHang1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("SĐT:");

        dateNgayNhap1.setPreferredSize(new java.awt.Dimension(146, 33));

        SachHoadonTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sách", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SachHoadonTable1.setRowHeight(40);
        jScrollPane3.setViewportView(SachHoadonTable1);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Tổng tiền:");

        lblTongTien1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTongTien1.setText("0");

        ThanhToanBtn1.setBackground(new java.awt.Color(0, 201, 167));
        ThanhToanBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ThanhToanBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pay.png"))); // NOI18N
        ThanhToanBtn1.setText("Thanh toán");
        ThanhToanBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        ThanhToanBtn1.setPreferredSize(new java.awt.Dimension(112, 43));
        ThanhToanBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThanhToanBtn1ActionPerformed(evt);
            }
        });

        HuyBtn1.setBackground(new java.awt.Color(0, 201, 167));
        HuyBtn1.setForeground(new java.awt.Color(255, 255, 255));
        HuyBtn1.setText("Hủy");
        HuyBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        HuyBtn1.setPreferredSize(new java.awt.Dimension(112, 43));
        HuyBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBtn1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setText("Đã trả:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setText("Còn lại:");

        lblDaTra1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDaTra1.setText("0");

        lblConLai1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblConLai1.setText("0");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setText("Khách hàng:");

        txtSDT1.setPreferredSize(new java.awt.Dimension(211, 30));
        txtSDT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDT1ActionPerformed(evt);
            }
        });

        txtMaNhanVien1.setPreferredSize(new java.awt.Dimension(211, 30));
        txtMaNhanVien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVien1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Mã nhân viên:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongTien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConLai1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(lblDaTra1)))
                .addGap(25, 25, 25))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addGap(219, 219, 219)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(HuyBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ThanhToanBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateNgayNhap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgayNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel28))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblTongTien1))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDaTra1)
                    .addComponent(jLabel20))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConLai1)
                    .addComponent(jLabel21))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HuyBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThanhToanBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        SachTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Sách", "NXB", "Năm XB", "Đơn giá", "Tồn kho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SachTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SachTable1.setShowGrid(true);
        jScrollPane4.setViewportView(SachTable1);

        javax.swing.GroupLayout body1Layout = new javax.swing.GroupLayout(body1);
        body1.setLayout(body1Layout);
        body1Layout.setHorizontalGroup(
            body1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        body1Layout.setVerticalGroup(
            body1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(body1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(body1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, 610));

        function1.setBackground(new java.awt.Color(255, 255, 255));
        function1.setPreferredSize(new java.awt.Dimension(996, 44));
        function1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimKiem1.setBackground(new java.awt.Color(251, 234, 255));
        TimKiem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        TimKiem1.setPreferredSize(new java.awt.Dimension(247, 43));
        TimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem1ActionPerformed(evt);
            }
        });
        function1.add(TimKiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 260, 30));

        TongSach3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TongSach3.setText("Tìm kiếm sách");
        function1.add(TongSach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 120, -1));

        Xuat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload.png"))); // NOI18N
        Xuat2.setBorder(null);
        Xuat2.setContentAreaFilled(false);
        Xuat2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Xuat2.setPreferredSize(new java.awt.Dimension(112, 43));
        Xuat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xuat2ActionPerformed(evt);
            }
        });
        function1.add(Xuat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 30, 30));

        Xuat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/download-to-storage-drive.png"))); // NOI18N
        Xuat3.setBorder(null);
        Xuat3.setContentAreaFilled(false);
        Xuat3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Xuat3.setPreferredSize(new java.awt.Dimension(112, 43));
        Xuat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xuat3ActionPerformed(evt);
            }
        });
        function1.add(Xuat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        XoaBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        XoaBtn1.setBorder(null);
        XoaBtn1.setContentAreaFilled(false);
        XoaBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XoaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtn1ActionPerformed(evt);
            }
        });
        function1.add(XoaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(132, 94, 194));
        jLabel6.setText("BÁN HÀNG");
        function1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        jPanel1.add(function1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiemActionPerformed

    private void ThanhToanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThanhToanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThanhToanBtnActionPerformed

    private void HuyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HuyBtnActionPerformed

    private void ThuTienThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThuTienThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThuTienThanhToanActionPerformed

    private void SoLuongLuuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoLuongLuuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoLuongLuuBtnActionPerformed

    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
        //CapNhatSach.setVisible(true);
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void txtKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachHangActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void txtKhachHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachHang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachHang1ActionPerformed

    private void ThanhToanBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThanhToanBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThanhToanBtn1ActionPerformed

    private void HuyBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HuyBtn1ActionPerformed

    private void txtSDT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDT1ActionPerformed

    private void txtMaNhanVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVien1ActionPerformed

    private void TimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiem1ActionPerformed

    private void Xuat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xuat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Xuat2ActionPerformed

    private void Xuat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xuat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Xuat3ActionPerformed

    private void XoaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XoaBtn1ActionPerformed




    public JButton getHuyBtn() {
        return HuyBtn;
    }

    public void setHuyBtn(JButton HuyBtn) {
        this.HuyBtn = HuyBtn;
    }

    public JDialog getNhapSoLuong() {
        return NhapSoLuong;
    }

    public void setNhapSoLuong(JDialog NhapSoLuong) {
        this.NhapSoLuong = NhapSoLuong;
    }

    public JTable getSachHoadonTable() {
        return SachHoadonTable;
    }

    public void setSachHoadonTable(JTable SachHoadonTable) {
        this.SachHoadonTable = SachHoadonTable;
    }

    public JTable getSachTable() {
        return SachTable;
    }

    public void setSachTable(JTable SachTable) {
        this.SachTable = SachTable;
    }

    public JButton getSoLuongHuyBtn() {
        return SoLuongHuyBtn;
    }

    public void setSoLuongHuyBtn(JButton SoLuongHuyBtn) {
        this.SoLuongHuyBtn = SoLuongHuyBtn;
    }

    public JButton getSoLuongLuuBtn() {
        return SoLuongLuuBtn;
    }

    public void setSoLuongLuuBtn(JButton SoLuongLuuBtn) {
        this.SoLuongLuuBtn = SoLuongLuuBtn;
    }

    public JButton getThanhToanBtn() {
        return ThanhToanBtn;
    }

    public void setThanhToanBtn(JButton ThanhToanBtn) {
        this.ThanhToanBtn = ThanhToanBtn;
    }

    public JDialog getThuTien() {
        return ThuTien;
    }

    public void setThuTien(JDialog ThuTien) {
        this.ThuTien = ThuTien;
    }

    public JButton getThuTienHuyBtn() {
        return ThuTienHuyBtn;
    }

    public void setThuTienHuyBtn(JButton ThuTienHuyBtn) {
        this.ThuTienHuyBtn = ThuTienHuyBtn;
    }

    public JButton getThuTienThanhToan() {
        return ThuTienThanhToan;
    }

    public void setThuTienThanhToan(JButton ThuTienThanhToan) {
        this.ThuTienThanhToan = ThuTienThanhToan;
    }

    public JTextField getTimKiem() {
        return TimKiem;
    }

    public void setTimKiem(JTextField TimKiem) {
        this.TimKiem = TimKiem;
    }

    public JLabel getTongSach2() {
        return TongSach2;
    }

    public void setTongSach2(JLabel TongSach2) {
        this.TongSach2 = TongSach2;
    }

    public JButton getXoaBtn() {
        return XoaBtn;
    }

    public void setXoaBtn(JButton XoaBtn) {
        this.XoaBtn = XoaBtn;
    }




    public JPanel getBody() {
        return body;
    }

    public void setBody(JPanel body) {
        this.body = body;
    }

    public JDateChooser getDateNgayNhap() {
        return dateNgayNhap;
    }

    public void setDateNgayNhap(JDateChooser dateNgayNhap) {
        this.dateNgayNhap = dateNgayNhap;
    }

    public JPanel getFunction() {
        return function;
    }

    public void setFunction(JPanel function) {
        this.function = function;
    }



    public JPanel getHeader3() {
        return header3;
    }

    public void setHeader3(JPanel header3) {
        this.header3 = header3;
    }

    public JPanel getHeader4() {
        return header4;
    }

    public void setHeader4(JPanel header4) {
        this.header4 = header4;
    }



    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }


    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JLabel getjLabel27() {
        return jLabel27;
    }

    public void setjLabel27(JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel10() {
        return jPanel10;
    }

    public void setjPanel10(JPanel jPanel10) {
        this.jPanel10 = jPanel10;
    }

    public JPanel getjPanel11() {
        return jPanel11;
    }

    public void setjPanel11(JPanel jPanel11) {
        this.jPanel11 = jPanel11;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }



    public JPanel getjPanel8() {
        return jPanel8;
    }

    public void setjPanel8(JPanel jPanel8) {
        this.jPanel8 = jPanel8;
    }

    public JPanel getjPanel9() {
        return jPanel9;
    }

    public void setjPanel9(JPanel jPanel9) {
        this.jPanel9 = jPanel9;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }



    public JLabel getLblConLai() {
        return lblConLai;
    }

    public void setLblConLai(JLabel lblConLai) {
        this.lblConLai = lblConLai;
    }

    public JLabel getLblDaTra() {
        return lblDaTra;
    }

    public void setLblDaTra(JLabel lblDaTra) {
        this.lblDaTra = lblDaTra;
    }

    public JLabel getLblTongTien() {
        return lblTongTien;
    }

    public void setLblTongTien(JLabel lblTongTien) {
        this.lblTongTien = lblTongTien;
    }

    public JTextField getTxtKhachHang() {
        return txtKhachHang;
    }

    public void setTxtKhachHang(JTextField txtKhachHang) {
        this.txtKhachHang = txtKhachHang;
    }

    public JTextField getTxtMaNhanVien() {
        return txtMaNhanVien;
    }

    public void setTxtMaNhanVien(JTextField txtMaNhanVien) {
        this.txtMaNhanVien = txtMaNhanVien;
    }

    public JTextField getTxtSDT() {
        return txtSDT;
    }

    public void setTxtSDT(JTextField txtSDT) {
        this.txtSDT = txtSDT;
    }

    public JTextField getTxtSoLuong() {
        return txtSoLuong;
    }

    public void setTxtSoLuong(JTextField txtSoLuong) {
        this.txtSoLuong = txtSoLuong;
    }

    public JTextField getTxtThuTien() {
        return txtThuTien;
    }

    public void setTxtThuTien(JTextField txtThuTien) {
        this.txtThuTien = txtThuTien;
    }

    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HuyBtn;
    private javax.swing.JButton HuyBtn1;
    private javax.swing.JDialog NhapSoLuong;
    private javax.swing.JTable SachHoadonTable;
    private javax.swing.JTable SachHoadonTable1;
    private javax.swing.JTable SachTable;
    private javax.swing.JTable SachTable1;
    private javax.swing.JButton SoLuongHuyBtn;
    private javax.swing.JButton SoLuongLuuBtn;
    private javax.swing.JButton ThanhToanBtn;
    private javax.swing.JButton ThanhToanBtn1;
    private javax.swing.JDialog ThuTien;
    private javax.swing.JButton ThuTienHuyBtn;
    private javax.swing.JButton ThuTienThanhToan;
    private javax.swing.JTextField TimKiem;
    private javax.swing.JTextField TimKiem1;
    private javax.swing.JLabel TongSach2;
    private javax.swing.JLabel TongSach3;
    private javax.swing.JButton XoaBtn;
    private javax.swing.JButton XoaBtn1;
    private javax.swing.JButton Xuat2;
    private javax.swing.JButton Xuat3;
    private javax.swing.JPanel body;
    private javax.swing.JPanel body1;
    private com.toedter.calendar.JDateChooser dateNgayNhap;
    private com.toedter.calendar.JDateChooser dateNgayNhap1;
    private javax.swing.JPanel function;
    private javax.swing.JPanel function1;
    private javax.swing.JPanel header3;
    private javax.swing.JPanel header4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblConLai;
    private javax.swing.JLabel lblConLai1;
    private javax.swing.JLabel lblDaTra;
    private javax.swing.JLabel lblDaTra1;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtKhachHang1;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMaNhanVien1;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSDT1;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtThuTien;
    // End of variables declaration//GEN-END:variables
}
