/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlinhasach.view;

import com.mycompany.quanlinhasach.controller.BanHangController;
import com.mycompany.quanlinhasach.controller.DauSachController;
import com.mycompany.quanlinhasach.controller.NhanVienController;
import com.mycompany.quanlinhasach.controller.SachController;
import com.mycompany.quanlinhasach.controller.ThongTinTaiKhoanController;
import com.mycompany.quanlinhasach.dao.CTHDDAO;
import com.mycompany.quanlinhasach.dao.CT_PhieuNhapSachDAO;
import com.mycompany.quanlinhasach.dao.DauSachDAO;
import com.mycompany.quanlinhasach.dao.HoaDonDAO;
import com.mycompany.quanlinhasach.dao.KhachHangDAO;
import com.mycompany.quanlinhasach.dao.NhanVienDAO;
import com.mycompany.quanlinhasach.dao.PhieuNhapSachDAO;
import com.mycompany.quanlinhasach.dao.QuyDinhDAO;
import com.mycompany.quanlinhasach.dao.SachDAO;
import com.mycompany.quanlinhasach.dao.TheLoaiDAO;
import com.mycompany.quanlinhasach.model.NhanVien;
import com.mycompany.quanlinhasach.controller.CaiDatQuyDinhController;
import com.mycompany.quanlinhasach.controller.KhachHangController;
import com.mycompany.quanlinhasach.dao.PhieuThuTienDAO;
import com.mycompany.quanlinhasach.view.ThongKe;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Color DefaultColor, MousedColor;
    private NhanVien nhanVien;
    
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel3.setVisible(false);
        
        DefaultColor = new Color(255, 255, 255);
        MousedColor = new Color(217, 217, 217);
        
        MainContent.removeAll();
        BanHang banHangView = new BanHang();

    // Tạo DAO kết nối cơ sở dữ liệu
        SachDAO sachdao = new SachDAO();
        KhachHangDAO khdao = new KhachHangDAO();
        HoaDonDAO hoadondao = new HoaDonDAO();
        CTHDDAO cthddao = new CTHDDAO();

        // Tạo controller
        BanHangController controller = new BanHangController(banHangView, sachdao,khdao, hoadondao, cthddao);
        MainContent.setLayout(new BorderLayout());
        MainContent.add(banHangView).setVisible(true);
    }
    
    public Main(NhanVien nhanVien) {
        initComponents();
        setLocationRelativeTo(null);
        jPanel3.setVisible(false);
        jLabel3.setText(nhanVien.getTenNhanVien());
        
        if(nhanVien.getMaQuyen() == 2){
            jpn_ThongKe.setVisible(false);
            jpn_HeThong.setVisible(false);
            jpn_NhanVien.setVisible(false);
        }

        DefaultColor = new Color(255, 255, 255);
        MousedColor = new Color(217, 217, 217);
        this.nhanVien = nhanVien;
        
        MainContent.removeAll();
        BanHang banHangView = new BanHang();

    // Tạo DAO kết nối cơ sở dữ liệu
        SachDAO sachdao = new SachDAO();
        KhachHangDAO khdao = new KhachHangDAO();
        HoaDonDAO hoadondao = new HoaDonDAO();
        CTHDDAO cthddao = new CTHDDAO();

        // Tạo controller
        BanHangController controller = new BanHangController(banHangView, sachdao,khdao, hoadondao, cthddao);
        MainContent.setLayout(new BorderLayout());
        MainContent.add(banHangView ).setVisible(true);
        
        MainContent.validate();
        MainContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpn_SanPham = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpn_DauSach = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpn_BanHang = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jpn_KhachHang = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jpn_ThongKe = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jpn_HeThong = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpn_NhanVien = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jpn_TaiKhoan = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jpn_DangXuat = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 40));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(132, 94, 194));
        jLabel5.setText("MENU");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 60, 40));

        jpn_SanPham.setBackground(new java.awt.Color(255, 255, 255));
        jpn_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_SanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_SanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_SanPhamMouseExited(evt);
            }
        });
        jpn_SanPham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(132, 94, 194));
        jLabel6.setText("Sản phẩm");
        jpn_SanPham.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book_2.png"))); // NOI18N
        jpn_SanPham.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jPanel3.add(jpn_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 50));

        jpn_DauSach.setBackground(new java.awt.Color(255, 255, 255));
        jpn_DauSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_DauSachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_DauSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_DauSachMouseExited(evt);
            }
        });
        jpn_DauSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book.png"))); // NOI18N
        jpn_DauSach.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(132, 94, 194));
        jLabel8.setText("Đầu sách");
        jpn_DauSach.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jPanel3.add(jpn_DauSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 50));

        jpn_BanHang.setBackground(new java.awt.Color(255, 255, 255));
        jpn_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_BanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_BanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_BanHangMouseExited(evt);
            }
        });
        jpn_BanHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping_cart.png"))); // NOI18N
        jpn_BanHang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(132, 94, 194));
        jLabel11.setText("Bán hàng");
        jpn_BanHang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jPanel3.add(jpn_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 50));

        jpn_KhachHang.setBackground(new java.awt.Color(255, 255, 255));
        jpn_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_KhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_KhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_KhachHangMouseExited(evt);
            }
        });
        jpn_KhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/person_apron.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jpn_KhachHang.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(132, 94, 194));
        jLabel13.setText("Khách hàng");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jpn_KhachHang.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jPanel3.add(jpn_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 50));

        jpn_ThongKe.setBackground(new java.awt.Color(255, 255, 255));
        jpn_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_ThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_ThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_ThongKeMouseExited(evt);
            }
        });
        jpn_ThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(132, 94, 194));
        jLabel15.setText("Thống kê");
        jpn_ThongKe.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finance.png"))); // NOI18N
        jpn_ThongKe.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jPanel3.add(jpn_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 50));

        jpn_HeThong.setBackground(new java.awt.Color(255, 255, 255));
        jpn_HeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_HeThongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_HeThongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_HeThongMouseExited(evt);
            }
        });
        jpn_HeThong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dns.png"))); // NOI18N
        jpn_HeThong.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(132, 94, 194));
        jLabel16.setText("Hệ thống");
        jpn_HeThong.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jPanel3.add(jpn_HeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, 50));

        jpn_NhanVien.setBackground(new java.awt.Color(255, 255, 255));
        jpn_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_NhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_NhanVienMouseExited(evt);
            }
        });
        jpn_NhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/badge.png"))); // NOI18N
        jpn_NhanVien.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel23.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(132, 94, 194));
        jLabel23.setText("Nhân viên");
        jpn_NhanVien.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jPanel3.add(jpn_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 180, 50));

        jpn_TaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        jpn_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_TaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_TaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_TaiKhoanMouseExited(evt);
            }
        });
        jpn_TaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account_circle.png"))); // NOI18N
        jpn_TaiKhoan.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(132, 94, 194));
        jLabel19.setText("Tài khoản");
        jpn_TaiKhoan.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jPanel3.add(jpn_TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 180, 50));

        jpn_DangXuat.setBackground(new java.awt.Color(255, 255, 255));
        jpn_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_DangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpn_DangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpn_DangXuatMouseExited(evt);
            }
        });
        jpn_DangXuat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(132, 94, 194));
        jLabel21.setText("Đăng xuất");
        jpn_DangXuat.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jpn_DangXuat.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jPanel3.add(jpn_DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 180, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 770));

        jPanel1.setBackground(new java.awt.Color(132, 94, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contact.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 30, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nguyễn Văn A");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 280, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        getContentPane().add(MainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x = 0;
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if( x == 0 ){
            jPanel3.show();
            jPanel3.setSize(x, 770);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            jPanel3.setSize(i, 770);
                        } 
                    }catch (InterruptedException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }    
            };th.start();
            x = 220;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if ( x == 220){
            jPanel3.setSize(220,770);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for (int i = 220; i >= 0; i-- ){
                            Thread.sleep(1);
                            jPanel3.setSize(i,770);
                        }
                    }catch (InterruptedException e) {
                        JOptionPane. showMessageDialog(null,e);
                    }
                }
            };th.start();
            x = 0;
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jpn_SanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_SanPhamMouseEntered
        // TODO add your handling code here:
        jpn_SanPham.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_SanPhamMouseEntered

    private void jpn_DauSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_DauSachMouseEntered
        // TODO add your handling code here:
        jpn_DauSach.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_DauSachMouseEntered

    private void jpn_BanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_BanHangMouseEntered
        // TODO add your handling code here:
        jpn_BanHang.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_BanHangMouseEntered

    private void jpn_KhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_KhachHangMouseEntered
        // TODO add your handling code here:
        jpn_KhachHang.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_KhachHangMouseEntered

    private void jpn_ThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_ThongKeMouseEntered
        // TODO add your handling code here:
        jpn_ThongKe.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_ThongKeMouseEntered

    private void jpn_HeThongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_HeThongMouseEntered
        // TODO add your handling code here:
        jpn_HeThong.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_HeThongMouseEntered

    private void jpn_TaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_TaiKhoanMouseEntered
        // TODO add your handling code here:
        jpn_TaiKhoan.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_TaiKhoanMouseEntered

    private void jpn_DangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_DangXuatMouseEntered
        // TODO add your handling code here:
        jpn_DangXuat.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_DangXuatMouseEntered

    private void jpn_SanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_SanPhamMouseExited
        // TODO add your handling code here:
        jpn_SanPham.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_SanPhamMouseExited

    private void jpn_DauSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_DauSachMouseExited
        // TODO add your handling code here:
        jpn_DauSach.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_DauSachMouseExited

    private void jpn_BanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_BanHangMouseExited
        // TODO add your handling code here:
        jpn_BanHang.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_BanHangMouseExited

    private void jpn_KhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_KhachHangMouseExited
        // TODO add your handling code here:
        jpn_KhachHang.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_KhachHangMouseExited

    private void jpn_ThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_ThongKeMouseExited
        // TODO add your handling code here:
        jpn_ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_ThongKeMouseExited

    private void jpn_HeThongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_HeThongMouseExited
        // TODO add your handling code here:
        jpn_HeThong.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_HeThongMouseExited

    private void jpn_TaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_TaiKhoanMouseExited
        // TODO add your handling code here:
        jpn_TaiKhoan.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_TaiKhoanMouseExited

    private void jpn_DangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_DangXuatMouseExited
        // TODO add your handling code here:
        jpn_DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_DangXuatMouseExited

    private void jpn_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_SanPhamMouseClicked
        // TODO add your handling code here:
        SanPham sanPhamView = null;
        SachDAO sachdao = null;
        PhieuNhapSachDAO pnsdao = null; 
        CT_PhieuNhapSachDAO ctPnsdao = null;
        try {
            // Tạo giao diện
            sanPhamView = new SanPham();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Tạo DAO kết nối cơ sở dữ liệu
        sachdao = new SachDAO();
        pnsdao = new PhieuNhapSachDAO();
        ctPnsdao = new CT_PhieuNhapSachDAO();
        // Tạo controller
        SachController controller = new SachController(sanPhamView, sachdao, pnsdao,ctPnsdao);

        // Cập nhật giao diện
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();

        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_SanPhamMouseClicked

    private void jpn_DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_DangXuatMouseClicked
        // TODO add your handling code here:
        int relly = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (relly == JOptionPane.YES_OPTION) {
            this.dispose();
            DangNhap a = new DangNhap();
            a.setVisible(true);
        }
    }//GEN-LAST:event_jpn_DangXuatMouseClicked

    private void jpn_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_BanHangMouseClicked
        BanHang banHangView = new BanHang();

    // Tạo DAO kết nối cơ sở dữ liệu
        SachDAO sachdao = new SachDAO();
        KhachHangDAO khdao = new KhachHangDAO();
        HoaDonDAO hoadondao = new HoaDonDAO();
        CTHDDAO cthddao = new CTHDDAO();

        // Tạo controller
        BanHangController controller = new BanHangController(banHangView, sachdao, khdao, hoadondao, cthddao);

        // Cập nhật giao diện
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();
        controller.loadTableData();
        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_BanHangMouseClicked

    private void jpn_DauSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_DauSachMouseClicked
        DauSach dauSachView = null;
        DauSachDAO dsdao = null;
        SachDAO dao = null;
        // Tạo giao diện
        dauSachView = new DauSach();

    // Tạo DAO kết nối cơ sở dữ liệu
        dsdao = new DauSachDAO();
        dao = new SachDAO();
        // Tạo controller
        DauSachController controller = new DauSachController(dauSachView,dsdao,dao);

        // Cập nhật giao diện
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();

        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_DauSachMouseClicked

    private void jpn_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_KhachHangMouseClicked
        QuanLiKhachHang view = new QuanLiKhachHang();
        KhachHangDAO khdao = new KhachHangDAO();
        PhieuThuTienDAO ttdao = new PhieuThuTienDAO();


        // Tạo controller
        KhachHangController controller = new KhachHangController(khdao,ttdao,view,nhanVien);

        // Cập nhật giao diện
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();

        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_KhachHangMouseClicked

    private void jpn_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_ThongKeMouseClicked
        ThongKe view = new ThongKe();
        
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(view).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();

        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_ThongKeMouseClicked

    private void jpn_HeThongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_HeThongMouseClicked
        CaiDatQuyDinh qdView = new CaiDatQuyDinh();
        QuyDinhDAO dao = new QuyDinhDAO();
        TheLoaiDAO tldao = new TheLoaiDAO();

        // Tạo controller
        CaiDatQuyDinhController controller = new CaiDatQuyDinhController(qdView,dao,tldao);

        // Cập nhật giao diện
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();

        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_HeThongMouseClicked

    private void jpn_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_TaiKhoanMouseClicked
        ThongTinTaiKhoan tkView = null;
        NhanVienDAO nhanVienDAO = null;

        // Tạo giao diện
        tkView= new ThongTinTaiKhoan();

    // Tạo DAO kết nối cơ sở dữ liệu
        nhanVienDAO = new NhanVienDAO();

        // Tạo controller
        ThongTinTaiKhoanController controller = new ThongTinTaiKhoanController(tkView,nhanVienDAO,nhanVien);

        // Cập nhật giao diện
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();

        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_TaiKhoanMouseClicked

    private void jpn_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_NhanVienMouseClicked
        // TODO add your handling code here:
        MainContent.removeAll();
//        QuanLiNhanVien qlnv = new QuanLiNhanVien();
        QuanLiNhanVien qlnv = new QuanLiNhanVien();
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        NhanVienController controller = new NhanVienController(qlnv, nhanVienDAO);
       
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true);
        MainContent.validate();
        MainContent.repaint();
        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jpn_NhanVienMouseClicked

    private void jpn_NhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_NhanVienMouseEntered
        // TODO add your handling code here:
        jpn_NhanVien.setBackground(MousedColor);
    }//GEN-LAST:event_jpn_NhanVienMouseEntered

    private void jpn_NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_NhanVienMouseExited
        // TODO add your handling code here:
        jpn_NhanVien.setBackground(DefaultColor);
    }//GEN-LAST:event_jpn_NhanVienMouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        QuanLiKhachHang view = new QuanLiKhachHang();
        KhachHangDAO khdao = new KhachHangDAO();
        PhieuThuTienDAO ttdao = new PhieuThuTienDAO();


        // Tạo controller
        KhachHangController controller = new KhachHangController(khdao,ttdao,view,nhanVien);

        // Cập nhật giao diện
        MainContent.removeAll();
        MainContent.setLayout(new BorderLayout());
        MainContent.add(controller.getView()).setVisible(true); // Hiển thị giao diện
        MainContent.validate();
        MainContent.repaint();

        jPanel3.setVisible(false);
        x = 0;
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpn_BanHang;
    private javax.swing.JPanel jpn_DangXuat;
    private javax.swing.JPanel jpn_DauSach;
    private javax.swing.JPanel jpn_HeThong;
    private javax.swing.JPanel jpn_KhachHang;
    private javax.swing.JPanel jpn_NhanVien;
    private javax.swing.JPanel jpn_SanPham;
    private javax.swing.JPanel jpn_TaiKhoan;
    private javax.swing.JPanel jpn_ThongKe;
    // End of variables declaration//GEN-END:variables
}
