/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlinhasach.view;

import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author TienDat
 */
public class QuanLiKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanLiKhachHang
     */
    public QuanLiKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemKhachHangDialog = new javax.swing.JDialog();
        userInfoPanel3 = new javax.swing.JPanel();
        userNameInputPanel3 = new javax.swing.JPanel();
        userNameLabel3 = new javax.swing.JLabel();
        khachHangNameTxtField = new javax.swing.JTextField();
        emailInputPanel1 = new javax.swing.JPanel();
        emailLabel1 = new javax.swing.JLabel();
        diaChiTxtField = new javax.swing.JTextField();
        phoneNumberInputPanel1 = new javax.swing.JPanel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        soDienThoaiTxtField = new javax.swing.JTextField();
        emailInputPanel2 = new javax.swing.JPanel();
        emailLabel2 = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        xacNhanHuyThemBtn = new javax.swing.JButton();
        xacNhanThemBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SuaKhachHangDialog = new javax.swing.JDialog();
        userInfoPanel4 = new javax.swing.JPanel();
        userNameInputPanel4 = new javax.swing.JPanel();
        userNameLabel4 = new javax.swing.JLabel();
        khachHangNameTxtField1 = new javax.swing.JTextField();
        emailInputPanel3 = new javax.swing.JPanel();
        emailLabel3 = new javax.swing.JLabel();
        diaChiTxtField1 = new javax.swing.JTextField();
        phoneNumberInputPanel2 = new javax.swing.JPanel();
        phoneNumberLabel2 = new javax.swing.JLabel();
        soDienThoaiTxtField1 = new javax.swing.JTextField();
        emailInputPanel4 = new javax.swing.JPanel();
        emailLabel4 = new javax.swing.JLabel();
        emailTxtField1 = new javax.swing.JTextField();
        xacNhanHuySuaBtn = new javax.swing.JButton();
        xacNhanSuaBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ThemPhieuThuTien = new javax.swing.JDialog();
        updateUserPanel = new javax.swing.JPanel();
        updateTitleLabel = new javax.swing.JLabel();
        userInfoPanel = new javax.swing.JPanel();
        userNameInputPanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        tenKhachThuTienTxtField = new javax.swing.JTextField();
        salaryInputPanel = new javax.swing.JPanel();
        salaryLabel = new javax.swing.JLabel();
        soTienThuTxtField = new javax.swing.JFormattedTextField();
        emailInputPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailKhachThuTienTxtField = new javax.swing.JTextField();
        birthdateInputPanel = new javax.swing.JPanel();
        birthdateLabel = new javax.swing.JLabel();
        diaChiKhachThuTienTxtField = new javax.swing.JTextField();
        startingDateInputPanel = new javax.swing.JPanel();
        startingDateLabel = new javax.swing.JLabel();
        ngayThuTienDateChooser = new com.toedter.calendar.JDateChooser();
        phoneNumberInputPanel = new javax.swing.JPanel();
        phoneNumberLabel = new javax.swing.JLabel();
        soDienThoaiThuTienTxtField = new javax.swing.JTextField();
        xacNhanHuyThemPhieuThu = new javax.swing.JButton();
        xacNhanThemPhieuThuTien = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        functionPanel = new javax.swing.JPanel();
        openPopUpPhieuThuTienBtn = new javax.swing.JButton();
        openPopUpThemKhachHangBtn = new javax.swing.JButton();
        searchKhachHangTxtField = new javax.swing.JTextField();
        openPopUpSuaKhachHangBtn = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        khachHangJScrollPane = new javax.swing.JScrollPane();
        khachHangTable = new javax.swing.JTable();

        ThemKhachHangDialog.setMinimumSize(new java.awt.Dimension(400, 420));
        ThemKhachHangDialog.setModal(true);
        ThemKhachHangDialog.setResizable(false);
        ThemKhachHangDialog.setSize(new java.awt.Dimension(380, 384));
        ThemKhachHangDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userInfoPanel3.setBackground(new java.awt.Color(255, 255, 255));
        userInfoPanel3.setMinimumSize(new java.awt.Dimension(400, 420));
        userInfoPanel3.setPreferredSize(new java.awt.Dimension(400, 420));
        userInfoPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameInputPanel3.setBackground(new java.awt.Color(255, 255, 255));
        userNameInputPanel3.setOpaque(false);
        userNameInputPanel3.setPreferredSize(new java.awt.Dimension(370, 64));

        userNameLabel3.setBackground(new java.awt.Color(255, 255, 255));
        userNameLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        userNameLabel3.setForeground(new java.awt.Color(111, 121, 121));
        userNameLabel3.setText("Họ và tên");
        userNameLabel3.setPreferredSize(new java.awt.Dimension(56, 28));

        khachHangNameTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        khachHangNameTxtField.setMinimumSize(new java.awt.Dimension(370, 36));
        khachHangNameTxtField.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout userNameInputPanel3Layout = new javax.swing.GroupLayout(userNameInputPanel3);
        userNameInputPanel3.setLayout(userNameInputPanel3Layout);
        userNameInputPanel3Layout.setHorizontalGroup(
            userNameInputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userNameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(khachHangNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        userNameInputPanel3Layout.setVerticalGroup(
            userNameInputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userNameInputPanel3Layout.createSequentialGroup()
                .addComponent(userNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(khachHangNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel3.add(userNameInputPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        emailInputPanel1.setBackground(new java.awt.Color(255, 255, 255));
        emailInputPanel1.setOpaque(false);
        emailInputPanel1.setPreferredSize(new java.awt.Dimension(370, 64));

        emailLabel1.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(111, 121, 121));
        emailLabel1.setText("Địa chỉ");
        emailLabel1.setPreferredSize(new java.awt.Dimension(56, 28));

        diaChiTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        diaChiTxtField.setMinimumSize(new java.awt.Dimension(370, 36));
        diaChiTxtField.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout emailInputPanel1Layout = new javax.swing.GroupLayout(emailInputPanel1);
        emailInputPanel1.setLayout(emailInputPanel1Layout);
        emailInputPanel1Layout.setHorizontalGroup(
            emailInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(diaChiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        emailInputPanel1Layout.setVerticalGroup(
            emailInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailInputPanel1Layout.createSequentialGroup()
                .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(diaChiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel3.add(emailInputPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        phoneNumberInputPanel1.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberInputPanel1.setOpaque(false);
        phoneNumberInputPanel1.setPreferredSize(new java.awt.Dimension(370, 64));

        phoneNumberLabel1.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        phoneNumberLabel1.setForeground(new java.awt.Color(111, 121, 121));
        phoneNumberLabel1.setText("Số điện thoại");
        phoneNumberLabel1.setPreferredSize(new java.awt.Dimension(56, 28));

        soDienThoaiTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        soDienThoaiTxtField.setMinimumSize(new java.awt.Dimension(370, 36));
        soDienThoaiTxtField.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout phoneNumberInputPanel1Layout = new javax.swing.GroupLayout(phoneNumberInputPanel1);
        phoneNumberInputPanel1.setLayout(phoneNumberInputPanel1Layout);
        phoneNumberInputPanel1Layout.setHorizontalGroup(
            phoneNumberInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phoneNumberLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(soDienThoaiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        phoneNumberInputPanel1Layout.setVerticalGroup(
            phoneNumberInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberInputPanel1Layout.createSequentialGroup()
                .addComponent(phoneNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(soDienThoaiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel3.add(phoneNumberInputPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        emailInputPanel2.setBackground(new java.awt.Color(255, 255, 255));
        emailInputPanel2.setOpaque(false);
        emailInputPanel2.setPreferredSize(new java.awt.Dimension(370, 64));

        emailLabel2.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailLabel2.setForeground(new java.awt.Color(111, 121, 121));
        emailLabel2.setText("Email");
        emailLabel2.setPreferredSize(new java.awt.Dimension(56, 28));

        emailTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailTxtField.setMinimumSize(new java.awt.Dimension(370, 36));
        emailTxtField.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout emailInputPanel2Layout = new javax.swing.GroupLayout(emailInputPanel2);
        emailInputPanel2.setLayout(emailInputPanel2Layout);
        emailInputPanel2Layout.setHorizontalGroup(
            emailInputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        emailInputPanel2Layout.setVerticalGroup(
            emailInputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailInputPanel2Layout.createSequentialGroup()
                .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel3.add(emailInputPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        xacNhanHuyThemBtn.setBackground(new java.awt.Color(0, 201, 167));
        xacNhanHuyThemBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        xacNhanHuyThemBtn.setForeground(new java.awt.Color(255, 255, 255));
        xacNhanHuyThemBtn.setText("Huỷ");
        xacNhanHuyThemBtn.setPreferredSize(new java.awt.Dimension(70, 34));
        userInfoPanel3.add(xacNhanHuyThemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        xacNhanThemBtn.setBackground(new java.awt.Color(0, 201, 167));
        xacNhanThemBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        xacNhanThemBtn.setForeground(new java.awt.Color(255, 255, 255));
        xacNhanThemBtn.setText("Thêm");
        xacNhanThemBtn.setPreferredSize(new java.awt.Dimension(80, 34));
        userInfoPanel3.add(xacNhanThemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(132, 94, 194));
        jLabel1.setText("Thêm khách hàng");
        userInfoPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        ThemKhachHangDialog.getContentPane().add(userInfoPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 390));

        SuaKhachHangDialog.setMinimumSize(new java.awt.Dimension(400, 420));
        SuaKhachHangDialog.setModal(true);
        SuaKhachHangDialog.setResizable(false);
        SuaKhachHangDialog.setSize(new java.awt.Dimension(380, 384));
        SuaKhachHangDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userInfoPanel4.setBackground(new java.awt.Color(255, 255, 255));
        userInfoPanel4.setMinimumSize(new java.awt.Dimension(400, 420));
        userInfoPanel4.setPreferredSize(new java.awt.Dimension(400, 420));
        userInfoPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameInputPanel4.setBackground(new java.awt.Color(255, 255, 255));
        userNameInputPanel4.setOpaque(false);
        userNameInputPanel4.setPreferredSize(new java.awt.Dimension(370, 64));

        userNameLabel4.setBackground(new java.awt.Color(255, 255, 255));
        userNameLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        userNameLabel4.setForeground(new java.awt.Color(111, 121, 121));
        userNameLabel4.setText("Họ và tên");
        userNameLabel4.setPreferredSize(new java.awt.Dimension(56, 28));

        khachHangNameTxtField1.setEditable(false);
        khachHangNameTxtField1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        khachHangNameTxtField1.setEnabled(false);
        khachHangNameTxtField1.setMinimumSize(new java.awt.Dimension(370, 36));
        khachHangNameTxtField1.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout userNameInputPanel4Layout = new javax.swing.GroupLayout(userNameInputPanel4);
        userNameInputPanel4.setLayout(userNameInputPanel4Layout);
        userNameInputPanel4Layout.setHorizontalGroup(
            userNameInputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userNameLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(khachHangNameTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        userNameInputPanel4Layout.setVerticalGroup(
            userNameInputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userNameInputPanel4Layout.createSequentialGroup()
                .addComponent(userNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(khachHangNameTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel4.add(userNameInputPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        emailInputPanel3.setBackground(new java.awt.Color(255, 255, 255));
        emailInputPanel3.setOpaque(false);
        emailInputPanel3.setPreferredSize(new java.awt.Dimension(370, 64));

        emailLabel3.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailLabel3.setForeground(new java.awt.Color(111, 121, 121));
        emailLabel3.setText("Địa chỉ");
        emailLabel3.setPreferredSize(new java.awt.Dimension(56, 28));

        diaChiTxtField1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        diaChiTxtField1.setMinimumSize(new java.awt.Dimension(370, 36));
        diaChiTxtField1.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout emailInputPanel3Layout = new javax.swing.GroupLayout(emailInputPanel3);
        emailInputPanel3.setLayout(emailInputPanel3Layout);
        emailInputPanel3Layout.setHorizontalGroup(
            emailInputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(diaChiTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        emailInputPanel3Layout.setVerticalGroup(
            emailInputPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailInputPanel3Layout.createSequentialGroup()
                .addComponent(emailLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(diaChiTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel4.add(emailInputPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        phoneNumberInputPanel2.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberInputPanel2.setOpaque(false);
        phoneNumberInputPanel2.setPreferredSize(new java.awt.Dimension(370, 64));

        phoneNumberLabel2.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        phoneNumberLabel2.setForeground(new java.awt.Color(111, 121, 121));
        phoneNumberLabel2.setText("Số điện thoại");
        phoneNumberLabel2.setPreferredSize(new java.awt.Dimension(56, 28));

        soDienThoaiTxtField1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        soDienThoaiTxtField1.setMinimumSize(new java.awt.Dimension(370, 36));
        soDienThoaiTxtField1.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout phoneNumberInputPanel2Layout = new javax.swing.GroupLayout(phoneNumberInputPanel2);
        phoneNumberInputPanel2.setLayout(phoneNumberInputPanel2Layout);
        phoneNumberInputPanel2Layout.setHorizontalGroup(
            phoneNumberInputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phoneNumberLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(soDienThoaiTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        phoneNumberInputPanel2Layout.setVerticalGroup(
            phoneNumberInputPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberInputPanel2Layout.createSequentialGroup()
                .addComponent(phoneNumberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(soDienThoaiTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel4.add(phoneNumberInputPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        emailInputPanel4.setBackground(new java.awt.Color(255, 255, 255));
        emailInputPanel4.setOpaque(false);
        emailInputPanel4.setPreferredSize(new java.awt.Dimension(370, 64));

        emailLabel4.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailLabel4.setForeground(new java.awt.Color(111, 121, 121));
        emailLabel4.setText("Email");
        emailLabel4.setPreferredSize(new java.awt.Dimension(56, 28));

        emailTxtField1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailTxtField1.setMinimumSize(new java.awt.Dimension(370, 36));
        emailTxtField1.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout emailInputPanel4Layout = new javax.swing.GroupLayout(emailInputPanel4);
        emailInputPanel4.setLayout(emailInputPanel4Layout);
        emailInputPanel4Layout.setHorizontalGroup(
            emailInputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(emailTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        emailInputPanel4Layout.setVerticalGroup(
            emailInputPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailInputPanel4Layout.createSequentialGroup()
                .addComponent(emailLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(emailTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel4.add(emailInputPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        xacNhanHuySuaBtn.setBackground(new java.awt.Color(0, 201, 167));
        xacNhanHuySuaBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        xacNhanHuySuaBtn.setForeground(new java.awt.Color(255, 255, 255));
        xacNhanHuySuaBtn.setText("Huỷ");
        xacNhanHuySuaBtn.setPreferredSize(new java.awt.Dimension(70, 34));
        userInfoPanel4.add(xacNhanHuySuaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        xacNhanSuaBtn.setBackground(new java.awt.Color(0, 201, 167));
        xacNhanSuaBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        xacNhanSuaBtn.setForeground(new java.awt.Color(255, 255, 255));
        xacNhanSuaBtn.setText("Cập nhật");
        xacNhanSuaBtn.setPreferredSize(new java.awt.Dimension(80, 34));
        userInfoPanel4.add(xacNhanSuaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 90, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(132, 94, 194));
        jLabel2.setText("Sửa khách hàng");
        userInfoPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        SuaKhachHangDialog.getContentPane().add(userInfoPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 510, 440));

        ThemPhieuThuTien.setSize(new java.awt.Dimension(810, 410));
        ThemPhieuThuTien.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateUserPanel.setBackground(new java.awt.Color(255, 255, 255));
        updateUserPanel.setMinimumSize(new java.awt.Dimension(810, 410));
        updateUserPanel.setPreferredSize(new java.awt.Dimension(810, 410));
        updateUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateTitleLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        updateTitleLabel.setForeground(new java.awt.Color(132, 94, 194));
        updateTitleLabel.setText("Thêm phiếu thu tiền");
        updateUserPanel.add(updateTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, -1, -1));

        userInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        userInfoPanel.setPreferredSize(new java.awt.Dimension(762, 356));
        userInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        userNameInputPanel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        userNameInputPanel.setPreferredSize(new java.awt.Dimension(370, 64));

        userNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        userNameLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(111, 121, 121));
        userNameLabel.setText("Họ và tên");
        userNameLabel.setPreferredSize(new java.awt.Dimension(56, 28));

        tenKhachThuTienTxtField.setEditable(false);
        tenKhachThuTienTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        tenKhachThuTienTxtField.setEnabled(false);
        tenKhachThuTienTxtField.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout userNameInputPanelLayout = new javax.swing.GroupLayout(userNameInputPanel);
        userNameInputPanel.setLayout(userNameInputPanelLayout);
        userNameInputPanelLayout.setHorizontalGroup(
            userNameInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tenKhachThuTienTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        userNameInputPanelLayout.setVerticalGroup(
            userNameInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userNameInputPanelLayout.createSequentialGroup()
                .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tenKhachThuTienTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel.add(userNameInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        salaryInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        salaryInputPanel.setPreferredSize(new java.awt.Dimension(370, 64));

        salaryLabel.setBackground(new java.awt.Color(255, 255, 255));
        salaryLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(111, 121, 121));
        salaryLabel.setText("Số tiền thu");
        salaryLabel.setPreferredSize(new java.awt.Dimension(56, 28));

        soTienThuTxtField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        soTienThuTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        javax.swing.GroupLayout salaryInputPanelLayout = new javax.swing.GroupLayout(salaryInputPanel);
        salaryInputPanel.setLayout(salaryInputPanelLayout);
        salaryInputPanelLayout.setHorizontalGroup(
            salaryInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryInputPanelLayout.createSequentialGroup()
                .addComponent(salaryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
            .addComponent(soTienThuTxtField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        salaryInputPanelLayout.setVerticalGroup(
            salaryInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryInputPanelLayout.createSequentialGroup()
                .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(soTienThuTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userInfoPanel.add(salaryInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        emailInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        emailInputPanel.setPreferredSize(new java.awt.Dimension(370, 64));

        emailLabel.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(111, 121, 121));
        emailLabel.setText("Email");
        emailLabel.setPreferredSize(new java.awt.Dimension(56, 28));

        emailKhachThuTienTxtField.setEditable(false);
        emailKhachThuTienTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        emailKhachThuTienTxtField.setEnabled(false);
        emailKhachThuTienTxtField.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout emailInputPanelLayout = new javax.swing.GroupLayout(emailInputPanel);
        emailInputPanel.setLayout(emailInputPanelLayout);
        emailInputPanelLayout.setHorizontalGroup(
            emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(emailKhachThuTienTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        emailInputPanelLayout.setVerticalGroup(
            emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailInputPanelLayout.createSequentialGroup()
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(emailKhachThuTienTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel.add(emailInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        birthdateInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        birthdateInputPanel.setPreferredSize(new java.awt.Dimension(370, 64));

        birthdateLabel.setBackground(new java.awt.Color(255, 255, 255));
        birthdateLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        birthdateLabel.setForeground(new java.awt.Color(111, 121, 121));
        birthdateLabel.setText("Địa chỉ");
        birthdateLabel.setPreferredSize(new java.awt.Dimension(56, 28));

        diaChiKhachThuTienTxtField.setEditable(false);
        diaChiKhachThuTienTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        diaChiKhachThuTienTxtField.setEnabled(false);

        javax.swing.GroupLayout birthdateInputPanelLayout = new javax.swing.GroupLayout(birthdateInputPanel);
        birthdateInputPanel.setLayout(birthdateInputPanelLayout);
        birthdateInputPanelLayout.setHorizontalGroup(
            birthdateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdateInputPanelLayout.createSequentialGroup()
                .addComponent(birthdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(diaChiKhachThuTienTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        birthdateInputPanelLayout.setVerticalGroup(
            birthdateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdateInputPanelLayout.createSequentialGroup()
                .addComponent(birthdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(diaChiKhachThuTienTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        userInfoPanel.add(birthdateInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        startingDateInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        startingDateInputPanel.setPreferredSize(new java.awt.Dimension(370, 64));

        startingDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        startingDateLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        startingDateLabel.setForeground(new java.awt.Color(111, 121, 121));
        startingDateLabel.setText("Ngày thu tiền");
        startingDateLabel.setPreferredSize(new java.awt.Dimension(56, 28));

        ngayThuTienDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        ngayThuTienDateChooser.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        javax.swing.GroupLayout startingDateInputPanelLayout = new javax.swing.GroupLayout(startingDateInputPanel);
        startingDateInputPanel.setLayout(startingDateInputPanelLayout);
        startingDateInputPanelLayout.setHorizontalGroup(
            startingDateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startingDateInputPanelLayout.createSequentialGroup()
                .addGroup(startingDateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startingDateInputPanelLayout.createSequentialGroup()
                        .addComponent(startingDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ngayThuTienDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        startingDateInputPanelLayout.setVerticalGroup(
            startingDateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startingDateInputPanelLayout.createSequentialGroup()
                .addComponent(startingDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ngayThuTienDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        userInfoPanel.add(startingDateInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        phoneNumberInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberInputPanel.setPreferredSize(new java.awt.Dimension(370, 64));

        phoneNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(111, 121, 121));
        phoneNumberLabel.setText("Số điện thoại");
        phoneNumberLabel.setPreferredSize(new java.awt.Dimension(56, 28));

        soDienThoaiThuTienTxtField.setEditable(false);
        soDienThoaiThuTienTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        soDienThoaiThuTienTxtField.setEnabled(false);
        soDienThoaiThuTienTxtField.setPreferredSize(new java.awt.Dimension(370, 36));

        javax.swing.GroupLayout phoneNumberInputPanelLayout = new javax.swing.GroupLayout(phoneNumberInputPanel);
        phoneNumberInputPanel.setLayout(phoneNumberInputPanelLayout);
        phoneNumberInputPanelLayout.setHorizontalGroup(
            phoneNumberInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(soDienThoaiThuTienTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        phoneNumberInputPanelLayout.setVerticalGroup(
            phoneNumberInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberInputPanelLayout.createSequentialGroup()
                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(soDienThoaiThuTienTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userInfoPanel.add(phoneNumberInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        xacNhanHuyThemPhieuThu.setBackground(new java.awt.Color(0, 201, 167));
        xacNhanHuyThemPhieuThu.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        xacNhanHuyThemPhieuThu.setForeground(new java.awt.Color(255, 255, 255));
        xacNhanHuyThemPhieuThu.setText("Huỷ");
        xacNhanHuyThemPhieuThu.setPreferredSize(new java.awt.Dimension(70, 34));
        userInfoPanel.add(xacNhanHuyThemPhieuThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        xacNhanThemPhieuThuTien.setBackground(new java.awt.Color(0, 201, 167));
        xacNhanThemPhieuThuTien.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        xacNhanThemPhieuThuTien.setForeground(new java.awt.Color(255, 255, 255));
        xacNhanThemPhieuThuTien.setText("Thêm");
        xacNhanThemPhieuThuTien.setPreferredSize(new java.awt.Dimension(80, 34));
        userInfoPanel.add(xacNhanThemPhieuThuTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 96, -1));

        updateUserPanel.add(userInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 47, -1, 340));

        ThemPhieuThuTien.getContentPane().add(updateUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setMinimumSize(new java.awt.Dimension(1080, 730));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1080, 723));

        functionPanel.setBackground(new java.awt.Color(255, 255, 255));
        functionPanel.setOpaque(false);
        functionPanel.setRequestFocusEnabled(false);
        functionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openPopUpPhieuThuTienBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dollar-bill.png"))); // NOI18N
        openPopUpPhieuThuTienBtn.setBorderPainted(false);
        openPopUpPhieuThuTienBtn.setContentAreaFilled(false);
        openPopUpPhieuThuTienBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openPopUpPhieuThuTienBtn.setFocusPainted(false);
        functionPanel.add(openPopUpPhieuThuTienBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 40, 40));

        openPopUpThemKhachHangBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addition.png"))); // NOI18N
        openPopUpThemKhachHangBtn.setBorderPainted(false);
        openPopUpThemKhachHangBtn.setContentAreaFilled(false);
        openPopUpThemKhachHangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openPopUpThemKhachHangBtn.setFocusPainted(false);
        functionPanel.add(openPopUpThemKhachHangBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 40, 40));

        searchKhachHangTxtField.setBackground(new java.awt.Color(251, 234, 255));
        searchKhachHangTxtField.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        searchKhachHangTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(132, 94, 194)));
        functionPanel.add(searchKhachHangTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 280, 32));

        openPopUpSuaKhachHangBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pen.jpg"))); // NOI18N
        openPopUpSuaKhachHangBtn.setBorderPainted(false);
        openPopUpSuaKhachHangBtn.setContentAreaFilled(false);
        openPopUpSuaKhachHangBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openPopUpSuaKhachHangBtn.setFocusPainted(false);
        functionPanel.add(openPopUpSuaKhachHangBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        searchLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchLabel.setText("Tìm kiếm khách hàng");
        functionPanel.add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(132, 94, 194));
        jLabel3.setText("KHÁCH HÀNG");
        functionPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        khachHangJScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        khachHangJScrollPane.setFocusable(false);
        khachHangJScrollPane.setPreferredSize(new java.awt.Dimension(1032, 598));

        khachHangTable.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        khachHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên khách hàng", "Địa chỉ", "Số điện thoại", "Email", "Tổng nợ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        khachHangTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        khachHangTable.setFocusable(false);
        khachHangTable.setPreferredSize(new java.awt.Dimension(1032, 570));
        khachHangTable.setRowHeight(44);
        khachHangTable.setShowGrid(false);
        khachHangTable.setShowVerticalLines(false);
        khachHangTable.getTableHeader().setReorderingAllowed(false);
        khachHangJScrollPane.setViewportView(khachHangTable);
        if (khachHangTable.getColumnModel().getColumnCount() > 0) {
            khachHangTable.getColumnModel().getColumn(0).setResizable(false);
            khachHangTable.getColumnModel().getColumn(1).setResizable(false);
            khachHangTable.getColumnModel().getColumn(2).setResizable(false);
            khachHangTable.getColumnModel().getColumn(3).setResizable(false);
            khachHangTable.getColumnModel().getColumn(4).setResizable(false);
            khachHangTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(khachHangJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(functionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(khachHangJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getBodyPanel() {
        return bodyPanel;
    }

    public void setBodyPanel(JPanel bodyPanel) {
        this.bodyPanel = bodyPanel;
    }

    public JPanel getFunctionPanel() {
        return functionPanel;
    }

    public void setFunctionPanel(JPanel functionPanel) {
        this.functionPanel = functionPanel;
    }

    public JScrollPane getKhachHangJScrollPane() {
        return khachHangJScrollPane;
    }

    public void setKhachHangJScrollPane(JScrollPane khachHangJScrollPane) {
        this.khachHangJScrollPane = khachHangJScrollPane;
    }

    public JTable getKhachHangTable() {
        return khachHangTable;
    }

    public void setKhachHangTable(JTable khachHangTable) {
        this.khachHangTable = khachHangTable;
    }

    public JButton getOpenPopUpPhieuThuTienBtn() {
        return openPopUpPhieuThuTienBtn;
    }

    public void setOpenPopUpPhieuThuTienBtn(JButton openPopUpPhieuThuTienBtn) {
        this.openPopUpPhieuThuTienBtn = openPopUpPhieuThuTienBtn;
    }

    public JButton getOpenPopUpSuaKhachHangBtn() {
        return openPopUpSuaKhachHangBtn;
    }

    public void setOpenPopUpSuaKhachHangBtn(JButton openPopUpSuaKhachHangBtn) {
        this.openPopUpSuaKhachHangBtn = openPopUpSuaKhachHangBtn;
    }

    public JButton getOpenPopUpThemKhachHangBtn() {
        return openPopUpThemKhachHangBtn;
    }

    public void setOpenPopUpThemKhachHangBtn(JButton openPopUpThemKhachHangBtn) {
        this.openPopUpThemKhachHangBtn = openPopUpThemKhachHangBtn;
    }

    public JTextField getSearchKhachHangTxtField() {
        return searchKhachHangTxtField;
    }

    public void setSearchKhachHangTxtField(JTextField searchKhachHangTxtField) {
        this.searchKhachHangTxtField = searchKhachHangTxtField;
    }

    public JLabel getSearchLabel() {
        return searchLabel;
    }

    public void setSearchLabel(JLabel searchLabel) {
        this.searchLabel = searchLabel;
    }

    public JDialog getSuaKhachHangDialog() {
        return SuaKhachHangDialog;
    }

    public void setSuaKhachHangDialog(JDialog SuaKhachHangDialog) {
        this.SuaKhachHangDialog = SuaKhachHangDialog;
    }

    public JDialog getThemKhachHangDialog() {
        return ThemKhachHangDialog;
    }

    public void setThemKhachHangDialog(JDialog ThemKhachHangDialog) {
        this.ThemKhachHangDialog = ThemKhachHangDialog;
    }

    public JTextField getDiaChiTxtField() {
        return diaChiTxtField;
    }

    public void setDiaChiTxtField(JTextField diaChiTxtField) {
        this.diaChiTxtField = diaChiTxtField;
    }

    public JTextField getDiaChiTxtField1() {
        return diaChiTxtField1;
    }

    public void setDiaChiTxtField1(JTextField diaChiTxtField1) {
        this.diaChiTxtField1 = diaChiTxtField1;
    }

    public JPanel getEmailInputPanel1() {
        return emailInputPanel1;
    }

    public void setEmailInputPanel1(JPanel emailInputPanel1) {
        this.emailInputPanel1 = emailInputPanel1;
    }

    public JPanel getEmailInputPanel2() {
        return emailInputPanel2;
    }

    public void setEmailInputPanel2(JPanel emailInputPanel2) {
        this.emailInputPanel2 = emailInputPanel2;
    }

    public JPanel getEmailInputPanel3() {
        return emailInputPanel3;
    }

    public void setEmailInputPanel3(JPanel emailInputPanel3) {
        this.emailInputPanel3 = emailInputPanel3;
    }

    public JPanel getEmailInputPanel4() {
        return emailInputPanel4;
    }

    public void setEmailInputPanel4(JPanel emailInputPanel4) {
        this.emailInputPanel4 = emailInputPanel4;
    }

    public JLabel getEmailLabel1() {
        return emailLabel1;
    }

    public void setEmailLabel1(JLabel emailLabel1) {
        this.emailLabel1 = emailLabel1;
    }

    public JLabel getEmailLabel2() {
        return emailLabel2;
    }

    public void setEmailLabel2(JLabel emailLabel2) {
        this.emailLabel2 = emailLabel2;
    }

    public JLabel getEmailLabel3() {
        return emailLabel3;
    }

    public void setEmailLabel3(JLabel emailLabel3) {
        this.emailLabel3 = emailLabel3;
    }

    public JLabel getEmailLabel4() {
        return emailLabel4;
    }

    public void setEmailLabel4(JLabel emailLabel4) {
        this.emailLabel4 = emailLabel4;
    }

    public JTextField getEmailTxtField() {
        return emailTxtField;
    }

    public void setEmailTxtField(JTextField emailTxtField) {
        this.emailTxtField = emailTxtField;
    }

    public JTextField getEmailTxtField1() {
        return emailTxtField1;
    }

    public void setEmailTxtField1(JTextField emailTxtField1) {
        this.emailTxtField1 = emailTxtField1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JTextField getKhachHangNameTxtField() {
        return khachHangNameTxtField;
    }

    public void setKhachHangNameTxtField(JTextField khachHangNameTxtField) {
        this.khachHangNameTxtField = khachHangNameTxtField;
    }

    public JTextField getKhachHangNameTxtField1() {
        return khachHangNameTxtField1;
    }

    public void setKhachHangNameTxtField1(JTextField khachHangNameTxtField1) {
        this.khachHangNameTxtField1 = khachHangNameTxtField1;
    }

    public JPanel getPhoneNumberInputPanel1() {
        return phoneNumberInputPanel1;
    }

    public void setPhoneNumberInputPanel1(JPanel phoneNumberInputPanel1) {
        this.phoneNumberInputPanel1 = phoneNumberInputPanel1;
    }

    public JPanel getPhoneNumberInputPanel2() {
        return phoneNumberInputPanel2;
    }

    public void setPhoneNumberInputPanel2(JPanel phoneNumberInputPanel2) {
        this.phoneNumberInputPanel2 = phoneNumberInputPanel2;
    }

    public JLabel getPhoneNumberLabel1() {
        return phoneNumberLabel1;
    }

    public void setPhoneNumberLabel1(JLabel phoneNumberLabel1) {
        this.phoneNumberLabel1 = phoneNumberLabel1;
    }

    public JLabel getPhoneNumberLabel2() {
        return phoneNumberLabel2;
    }

    public void setPhoneNumberLabel2(JLabel phoneNumberLabel2) {
        this.phoneNumberLabel2 = phoneNumberLabel2;
    }

    public JTextField getSoDienThoaiTxtField() {
        return soDienThoaiTxtField;
    }

    public void setSoDienThoaiTxtField(JTextField soDienThoaiTxtField) {
        this.soDienThoaiTxtField = soDienThoaiTxtField;
    }

    public JTextField getSoDienThoaiTxtField1() {
        return soDienThoaiTxtField1;
    }

    public void setSoDienThoaiTxtField1(JTextField soDienThoaiTxtField1) {
        this.soDienThoaiTxtField1 = soDienThoaiTxtField1;
    }

    public JPanel getUserInfoPanel3() {
        return userInfoPanel3;
    }

    public void setUserInfoPanel3(JPanel userInfoPanel3) {
        this.userInfoPanel3 = userInfoPanel3;
    }

    public JPanel getUserInfoPanel4() {
        return userInfoPanel4;
    }

    public void setUserInfoPanel4(JPanel userInfoPanel4) {
        this.userInfoPanel4 = userInfoPanel4;
    }

    public JPanel getUserNameInputPanel3() {
        return userNameInputPanel3;
    }

    public void setUserNameInputPanel3(JPanel userNameInputPanel3) {
        this.userNameInputPanel3 = userNameInputPanel3;
    }

    public JPanel getUserNameInputPanel4() {
        return userNameInputPanel4;
    }

    public void setUserNameInputPanel4(JPanel userNameInputPanel4) {
        this.userNameInputPanel4 = userNameInputPanel4;
    }

    public JLabel getUserNameLabel3() {
        return userNameLabel3;
    }

    public void setUserNameLabel3(JLabel userNameLabel3) {
        this.userNameLabel3 = userNameLabel3;
    }

    public JLabel getUserNameLabel4() {
        return userNameLabel4;
    }

    public void setUserNameLabel4(JLabel userNameLabel4) {
        this.userNameLabel4 = userNameLabel4;
    }

    public JButton getXacNhanHuySuaBtn() {
        return xacNhanHuySuaBtn;
    }

    public void setXacNhanHuySuaBtn(JButton xacNhanHuySuaBtn) {
        this.xacNhanHuySuaBtn = xacNhanHuySuaBtn;
    }

    public JButton getXacNhanHuyThemBtn() {
        return xacNhanHuyThemBtn;
    }

    public void setXacNhanHuyThemBtn(JButton xacNhanHuyThemBtn) {
        this.xacNhanHuyThemBtn = xacNhanHuyThemBtn;
    }

    public JButton getXacNhanSuaBtn() {
        return xacNhanSuaBtn;
    }

    public void setXacNhanSuaBtn(JButton xacNhanSuaBtn) {
        this.xacNhanSuaBtn = xacNhanSuaBtn;
    }

    public JButton getXacNhanThemBtn() {
        return xacNhanThemBtn;
    }

    public void setXacNhanThemBtn(JButton xacNhanThemBtn) {
        this.xacNhanThemBtn = xacNhanThemBtn;
    }

    public JDialog getThemPhieuThuTien() {
        return ThemPhieuThuTien;
    }

    public void setThemPhieuThuTien(JDialog ThemPhieuThuTien) {
        this.ThemPhieuThuTien = ThemPhieuThuTien;
    }

    public JPanel getBirthdateInputPanel() {
        return birthdateInputPanel;
    }

    public void setBirthdateInputPanel(JPanel birthdateInputPanel) {
        this.birthdateInputPanel = birthdateInputPanel;
    }

    public JLabel getBirthdateLabel() {
        return birthdateLabel;
    }

    public void setBirthdateLabel(JLabel birthdateLabel) {
        this.birthdateLabel = birthdateLabel;
    }

    public JTextField getDiaChiKhachThuTienTxtField() {
        return diaChiKhachThuTienTxtField;
    }

    public void setDiaChiKhachThuTienTxtField(JTextField diaChiKhachThuTienTxtField) {
        this.diaChiKhachThuTienTxtField = diaChiKhachThuTienTxtField;
    }

    public JPanel getEmailInputPanel() {
        return emailInputPanel;
    }

    public void setEmailInputPanel(JPanel emailInputPanel) {
        this.emailInputPanel = emailInputPanel;
    }

    public JTextField getEmailKhachThuTienTxtField() {
        return emailKhachThuTienTxtField;
    }

    public void setEmailKhachThuTienTxtField(JTextField emailKhachThuTienTxtField) {
        this.emailKhachThuTienTxtField = emailKhachThuTienTxtField;
    }

    public JLabel getEmailLabel() {
        return emailLabel;
    }

    public void setEmailLabel(JLabel emailLabel) {
        this.emailLabel = emailLabel;
    }

    public JDateChooser getNgayThuTienDateChooser() {
        return ngayThuTienDateChooser;
    }

    public void setNgayThuTienDateChooser(JDateChooser ngayThuTienDateChooser) {
        this.ngayThuTienDateChooser = ngayThuTienDateChooser;
    }

    public JPanel getPhoneNumberInputPanel() {
        return phoneNumberInputPanel;
    }

    public void setPhoneNumberInputPanel(JPanel phoneNumberInputPanel) {
        this.phoneNumberInputPanel = phoneNumberInputPanel;
    }

    public JLabel getPhoneNumberLabel() {
        return phoneNumberLabel;
    }

    public void setPhoneNumberLabel(JLabel phoneNumberLabel) {
        this.phoneNumberLabel = phoneNumberLabel;
    }

    public JPanel getSalaryInputPanel() {
        return salaryInputPanel;
    }

    public void setSalaryInputPanel(JPanel salaryInputPanel) {
        this.salaryInputPanel = salaryInputPanel;
    }

    public JLabel getSalaryLabel() {
        return salaryLabel;
    }

    public void setSalaryLabel(JLabel salaryLabel) {
        this.salaryLabel = salaryLabel;
    }

    public JTextField getSoDienThoaiThuTienTxtField() {
        return soDienThoaiThuTienTxtField;
    }

    public void setSoDienThoaiThuTienTxtField(JTextField soDienThoaiThuTienTxtField) {
        this.soDienThoaiThuTienTxtField = soDienThoaiThuTienTxtField;
    }

    public JFormattedTextField getSoTienThuTxtField() {
        return soTienThuTxtField;
    }

    public void setSoTienThuTxtField(JFormattedTextField soTienThuTxtField) {
        this.soTienThuTxtField = soTienThuTxtField;
    }

    public JPanel getStartingDateInputPanel() {
        return startingDateInputPanel;
    }

    public void setStartingDateInputPanel(JPanel startingDateInputPanel) {
        this.startingDateInputPanel = startingDateInputPanel;
    }

    public JLabel getStartingDateLabel() {
        return startingDateLabel;
    }

    public void setStartingDateLabel(JLabel startingDateLabel) {
        this.startingDateLabel = startingDateLabel;
    }

    public JTextField getTenKhachThuTienTxtField() {
        return tenKhachThuTienTxtField;
    }

    public void setTenKhachThuTienTxtField(JTextField tenKhachThuTienTxtField) {
        this.tenKhachThuTienTxtField = tenKhachThuTienTxtField;
    }

    public JLabel getUpdateTitleLabel() {
        return updateTitleLabel;
    }

    public void setUpdateTitleLabel(JLabel updateTitleLabel) {
        this.updateTitleLabel = updateTitleLabel;
    }

    public JPanel getUpdateUserPanel() {
        return updateUserPanel;
    }

    public void setUpdateUserPanel(JPanel updateUserPanel) {
        this.updateUserPanel = updateUserPanel;
    }

    public JPanel getUserInfoPanel() {
        return userInfoPanel;
    }

    public void setUserInfoPanel(JPanel userInfoPanel) {
        this.userInfoPanel = userInfoPanel;
    }

    public JPanel getUserNameInputPanel() {
        return userNameInputPanel;
    }

    public void setUserNameInputPanel(JPanel userNameInputPanel) {
        this.userNameInputPanel = userNameInputPanel;
    }

    public JLabel getUserNameLabel() {
        return userNameLabel;
    }

    public void setUserNameLabel(JLabel userNameLabel) {
        this.userNameLabel = userNameLabel;
    }

    public JButton getXacNhanHuyThemPhieuThu() {
        return xacNhanHuyThemPhieuThu;
    }

    public void setXacNhanHuyThemPhieuThu(JButton xacNhanHuyThemPhieuThu) {
        this.xacNhanHuyThemPhieuThu = xacNhanHuyThemPhieuThu;
    }

    public JButton getXacNhanThemPhieuThuTien() {
        return xacNhanThemPhieuThuTien;
    }

    public void setXacNhanThemPhieuThuTien(JButton xacNhanThemPhieuThuTien) {
        this.xacNhanThemPhieuThuTien = xacNhanThemPhieuThuTien;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SuaKhachHangDialog;
    private javax.swing.JDialog ThemKhachHangDialog;
    private javax.swing.JDialog ThemPhieuThuTien;
    private javax.swing.JPanel birthdateInputPanel;
    private javax.swing.JLabel birthdateLabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JTextField diaChiKhachThuTienTxtField;
    private javax.swing.JTextField diaChiTxtField;
    private javax.swing.JTextField diaChiTxtField1;
    private javax.swing.JPanel emailInputPanel;
    private javax.swing.JPanel emailInputPanel1;
    private javax.swing.JPanel emailInputPanel2;
    private javax.swing.JPanel emailInputPanel3;
    private javax.swing.JPanel emailInputPanel4;
    private javax.swing.JTextField emailKhachThuTienTxtField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel emailLabel3;
    private javax.swing.JLabel emailLabel4;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JTextField emailTxtField1;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane khachHangJScrollPane;
    private javax.swing.JTextField khachHangNameTxtField;
    private javax.swing.JTextField khachHangNameTxtField1;
    private javax.swing.JTable khachHangTable;
    private com.toedter.calendar.JDateChooser ngayThuTienDateChooser;
    private javax.swing.JButton openPopUpPhieuThuTienBtn;
    private javax.swing.JButton openPopUpSuaKhachHangBtn;
    private javax.swing.JButton openPopUpThemKhachHangBtn;
    private javax.swing.JPanel phoneNumberInputPanel;
    private javax.swing.JPanel phoneNumberInputPanel1;
    private javax.swing.JPanel phoneNumberInputPanel2;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JLabel phoneNumberLabel2;
    private javax.swing.JPanel salaryInputPanel;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JTextField searchKhachHangTxtField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField soDienThoaiThuTienTxtField;
    private javax.swing.JTextField soDienThoaiTxtField;
    private javax.swing.JTextField soDienThoaiTxtField1;
    private javax.swing.JFormattedTextField soTienThuTxtField;
    private javax.swing.JPanel startingDateInputPanel;
    private javax.swing.JLabel startingDateLabel;
    private javax.swing.JTextField tenKhachThuTienTxtField;
    private javax.swing.JLabel updateTitleLabel;
    private javax.swing.JPanel updateUserPanel;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JPanel userInfoPanel3;
    private javax.swing.JPanel userInfoPanel4;
    private javax.swing.JPanel userNameInputPanel;
    private javax.swing.JPanel userNameInputPanel3;
    private javax.swing.JPanel userNameInputPanel4;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNameLabel3;
    private javax.swing.JLabel userNameLabel4;
    private javax.swing.JButton xacNhanHuySuaBtn;
    private javax.swing.JButton xacNhanHuyThemBtn;
    private javax.swing.JButton xacNhanHuyThemPhieuThu;
    private javax.swing.JButton xacNhanSuaBtn;
    private javax.swing.JButton xacNhanThemBtn;
    private javax.swing.JButton xacNhanThemPhieuThuTien;
    // End of variables declaration//GEN-END:variables
}
