/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlinhasach.view;


import com.mycompany.quanlinhasach.dao.DauSachDAO;
import com.mycompany.quanlinhasach.dao.NhaXuatBanDAO;
import com.mycompany.quanlinhasach.dao.SachDAO;

import com.mycompany.quanlinhasach.database.JDBCUtil;
import com.mycompany.quanlinhasach.model.NhaXuatBan;
import com.mycompany.quanlinhasach.model.Sach;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JYearChooser;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author NGUYEN MY NGAN
 */
public class SanPham extends javax.swing.JPanel {
    
    /**
     * Creates new form SanPham1
     * @throws java.sql.SQLException
     */
    public SanPham() throws SQLException {
        initComponents();
  //      JDialog capNhatSachDialog = CapNhatSach.get;
       
        
        // Khởi tạo DAO và kết nối cơ sở dữ liệu
        Connection connection = JDBCUtil.getConnection(); // Phải có lớp DatabaseConnection để lấy kết nối
//        SachDAO sachDAO = new SachDAO(connection); // Khởi tạo DAO
//
//
//
//        // Khởi tạo controller
//        SachController controller = new SachController(sachDAO, table);
//        SachController controller1 = new SachController(sachDAO, table1);
        // Đổ dữ liệu vào JComboBox
        loadNhaXuatBanToComboBox(); 
        loadDauSachToComboBox();


        // Xử lý hành động trên bảng
//        TableActionEvent event = new TableActionEvent() {
//            @Override
//            public void onEdit(int row) {
//                System.out.println("Edit row : " + row);
//            }
//
//            @Override
//            public void onDelete(int row) {
//                if (table.isEditing()) {
//                    table.getCellEditor().stopCellEditing();
//                }
//                DefaultTableModel model = (DefaultTableModel) table.getModel();
//                model.removeRow(row);
//            }
//
//            @Override
//            public void onView(int row) {
//                System.out.println("View row : " + row);
//            }
//        };
//
//        table.getColumnModel().getColumn(7).setCellRenderer(new TableActionCellRender());
//        table.getColumnModel().getColumn(7).setCellEditor(new TableActionCellEditor(event));
//        table.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
//            @Override
//            public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
//                setHorizontalAlignment(SwingConstants.RIGHT);
//                return super.getTableCellRendererComponent(jtable, o, bln, bln1, i, i1);
//            }
//        });

        // Xử lý sự kiện nút Thêm
//        ThemBtn.addActionListener(e -> {
//            try {
//                String tenSach = (String) DauSachCmb.getSelectedItem();
//                String nhaXuatBan = (String) NhaXuatBanCmb.getSelectedItem();
//                int namXuatBan = NamXBchooser.getYear();
//                int soLuong = Integer.parseInt(txtSoLuong.getText());
//                int donGia = Integer.parseInt(txtDonGia.getText());
//                String ngayNhap = new SimpleDateFormat("yyyy-MM-dd").format(NgayNhapChooser.getDate());
//
//                // Gọi controller để kiểm tra và thêm sách
//                controller.kiemTraVaThemSach(tenSach, nhaXuatBan, namXuatBan, soLuong, donGia, ngayNhap);
//            } catch (NumberFormatException ex) {
//                JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng và đủ định dạng dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            }
//        });


    }



// 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void loadNhaXuatBanToComboBox() {
        // Kết nối đến cơ sở dữ liệu
        try (Connection connection = JDBCUtil.getConnection()) {

            // Tạo DAO và gọi phương thức để lấy danh sách nhà xuất bản
            NhaXuatBanDAO nhaXuatBanDAO = new NhaXuatBanDAO(connection);
            List<NhaXuatBan> nhaXuatBans = nhaXuatBanDAO.getAllNhaXuatBan();

            // Tạo DefaultComboBoxModel để gán vào JComboBox
            DefaultComboBoxModel<String> cbbModel = new DefaultComboBoxModel<>();
            
            // Duyệt qua danh sách các nhà xuất bản và thêm vào ComboBox
            for (NhaXuatBan nhaXuatBan : nhaXuatBans) {
                cbbModel.addElement(nhaXuatBan.getTenNhaXuatBan());
            }

            // Gán DefaultComboBoxModel vào JComboBox
            SuaNXBCmb.setModel(cbbModel);
            NhaXuatBanCmb.setModel(cbbModel);
            NhaXuatBanCmb1.setModel(cbbModel);

        } catch (SQLException e) {
            e.printStackTrace();  // In lỗi nếu có
        }
    }

    public void loadDauSachToComboBox() {
        try {
            // Tạo đối tượng DauSachDAO
            DauSachDAO dauSachDAO = new DauSachDAO();

            // Lấy danh sách đầu sách từ DAO
            List<com.mycompany.quanlinhasach.model.DauSachModel> dauSachs = dauSachDAO.selectAll();

            // Tạo DefaultComboBoxModel để gán vào JComboBox
            DefaultComboBoxModel<String> cbbModel = new DefaultComboBoxModel<>();

            // Duyệt qua danh sách đầu sách và thêm vào ComboBox
            for (com.mycompany.quanlinhasach.model.DauSachModel dauSach : dauSachs) {
                cbbModel.addElement(dauSach.getTenDauSach()); // Sử dụng phương thức trong model
            }

            // Gán DefaultComboBoxModel vào JComboBox
            SuaTenDauSachCmb.setModel(cbbModel);
            DauSachCmb.setModel(cbbModel);
            DauSachCmb1.setModel(cbbModel);

        } catch (Exception e) {
            e.printStackTrace(); // In lỗi nếu có
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NhapKho = new javax.swing.JDialog();
        mainNhapKho = new javax.swing.JPanel();
        header1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bodyNhapKho = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        DauSachCmb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        NgayNhapChooser = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        NhaXuatBanCmb = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        NamXBchooser = new com.toedter.calendar.JYearChooser();
        jLabel15 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ThemBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NhapTable = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        ThoatNhapKhoBtn = new javax.swing.JButton();
        NhapSachBtn = new javax.swing.JButton();
        ThemSach = new javax.swing.JDialog();
        mainThemSach = new javax.swing.JPanel();
        header2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        bodyNhapKho1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        DauSachCmb1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        NhaXuatBanCmb1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        NamXBchooser1 = new com.toedter.calendar.JYearChooser();
        jLabel22 = new javax.swing.JLabel();
        txtDonGia1 = new javax.swing.JTextField();
        ThemBtn1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        ThoatBtn = new javax.swing.JButton();
        LuuBtn = new javax.swing.JButton();
        CapNhatSach = new javax.swing.JDialog();
        header3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        SuaDonGiatxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        SuaNXBCmb = new javax.swing.JComboBox<>();
        SuaThoatBtn = new javax.swing.JButton();
        SuaLuuBtn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        SuaNamXBChooser = new com.toedter.calendar.JYearChooser();
        SuaTenDauSachCmb = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        SuaTacGiaCmb = new javax.swing.JTextField();
        fileLabel = new javax.swing.JLabel();
        SuaSoLuongtxt = new javax.swing.JTextField();
        function = new javax.swing.JPanel();
        TimKiem = new javax.swing.JTextField();
        TongSach = new javax.swing.JLabel();
        ThemSachBtn = new javax.swing.JButton();
        NhapKhoBtn = new javax.swing.JButton();
        lblTongSach = new javax.swing.JLabel();
        XoaBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        TongSach1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SachTable = new javax.swing.JTable();

        NhapKho.setBackground(new java.awt.Color(255, 255, 255));
        NhapKho.setMinimumSize(new java.awt.Dimension(954, 654));
        NhapKho.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainNhapKho.setBackground(new java.awt.Color(255, 255, 255));
        mainNhapKho.setPreferredSize(new java.awt.Dimension(954, 624));
        mainNhapKho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setBackground(new java.awt.Color(132, 94, 194));
        header1.setPreferredSize(new java.awt.Dimension(954, 30));
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PHIẾU NHẬP SÁCH");
        header1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 142, -1));

        mainNhapKho.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 33));

        bodyNhapKho.setBackground(new java.awt.Color(255, 255, 255));
        bodyNhapKho.setPreferredSize(new java.awt.Dimension(954, 594));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Tên sách:");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, 75, -1));

        DauSachCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danh sách đầu sách", "Item 2", "Item 3", "Item 4" }));
        DauSachCmb.setPreferredSize(new java.awt.Dimension(181, 33));
        DauSachCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DauSachCmbActionPerformed(evt);
            }
        });
        jPanel13.add(DauSachCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 28, -1, -1));

        jLabel11.setText("Ngày nhập:");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 73, -1, -1));
        jPanel13.add(NgayNhapChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 95, 181, 33));

        jLabel12.setText("Nhà xuất bản:");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 6, 94, -1));

        NhaXuatBanCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NhaXuatBanCmb.setPreferredSize(new java.awt.Dimension(181, 33));
        NhaXuatBanCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhaXuatBanCmbActionPerformed(evt);
            }
        });
        jPanel13.add(NhaXuatBanCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 28, -1, -1));

        jLabel13.setText("Số lượng nhập:");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 73, -1, -1));

        txtSoLuong.setPreferredSize(new java.awt.Dimension(181, 33));
        jPanel13.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 95, -1, -1));

        jLabel14.setText("Năm xuất bản:");
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 6, -1, -1));

        NamXBchooser.setPreferredSize(new java.awt.Dimension(181, 33));
        jPanel13.add(NamXBchooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 28, -1, -1));

        jLabel15.setText("Đơn giá nhập:");
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 73, -1, -1));

        txtDonGia.setPreferredSize(new java.awt.Dimension(181, 33));
        jPanel13.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 95, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 201, 167));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open-book.png"))); // NOI18N
        jButton3.setText("Sách mới");
        jButton3.setPreferredSize(new java.awt.Dimension(111, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 28, 140, -1));

        ThemBtn.setBackground(new java.awt.Color(0, 201, 167));
        ThemBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        ThemBtn.setText("Thêm");
        ThemBtn.setPreferredSize(new java.awt.Dimension(111, 33));
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });
        jPanel13.add(ThemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 95, 140, -1));

        NhapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sách", "Tác giả", "Nhà xuất bản", "Năm XB", "Số lượng nhập", "Đơn giá nhập", "Ngày nhập", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NhapTable.setRowHeight(40);
        jScrollPane2.setViewportView(NhapTable);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ThoatNhapKhoBtn.setBackground(new java.awt.Color(0, 201, 167));
        ThoatNhapKhoBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThoatNhapKhoBtn.setText("Thoát");
        ThoatNhapKhoBtn.setPreferredSize(new java.awt.Dimension(116, 35));
        ThoatNhapKhoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatNhapKhoBtnActionPerformed(evt);
            }
        });
        jPanel12.add(ThoatNhapKhoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 6, -1, -1));

        NhapSachBtn.setBackground(new java.awt.Color(0, 201, 167));
        NhapSachBtn.setForeground(new java.awt.Color(255, 255, 255));
        NhapSachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhapkho.png"))); // NOI18N
        NhapSachBtn.setText("Nhập kho");
        NhapSachBtn.setPreferredSize(new java.awt.Dimension(116, 35));
        jPanel12.add(NhapSachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 6, 130, -1));

        javax.swing.GroupLayout bodyNhapKhoLayout = new javax.swing.GroupLayout(bodyNhapKho);
        bodyNhapKho.setLayout(bodyNhapKhoLayout);
        bodyNhapKhoLayout.setHorizontalGroup(
            bodyNhapKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyNhapKhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyNhapKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyNhapKhoLayout.setVerticalGroup(
            bodyNhapKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyNhapKhoLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        mainNhapKho.add(bodyNhapKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, -1, -1));

        NhapKho.getContentPane().add(mainNhapKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ThemSach.setMinimumSize(new java.awt.Dimension(954, 680));
        ThemSach.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainThemSach.setBackground(new java.awt.Color(255, 255, 255));
        mainThemSach.setPreferredSize(new java.awt.Dimension(954, 624));
        mainThemSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header2.setBackground(new java.awt.Color(132, 94, 194));
        header2.setPreferredSize(new java.awt.Dimension(954, 30));
        header2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("THÊM SÁCH MỚI");
        header2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 142, -1));

        mainThemSach.add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 33));

        bodyNhapKho1.setBackground(new java.awt.Color(255, 255, 255));
        bodyNhapKho1.setPreferredSize(new java.awt.Dimension(954, 594));
        bodyNhapKho1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Tên sách:");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, 94, -1));

        DauSachCmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danh sách đầu sách", "Item 2", "Item 3", "Item 4" }));
        DauSachCmb1.setPreferredSize(new java.awt.Dimension(181, 33));
        DauSachCmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DauSachCmb1ActionPerformed(evt);
            }
        });
        jPanel14.add(DauSachCmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 28, -1, -1));

        jLabel19.setText("Nhà xuất bản:");
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 6, 94, -1));

        NhaXuatBanCmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NhaXuatBanCmb1.setPreferredSize(new java.awt.Dimension(181, 33));
        NhaXuatBanCmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhaXuatBanCmb1ActionPerformed(evt);
            }
        });
        jPanel14.add(NhaXuatBanCmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 28, -1, -1));

        jLabel21.setText("Năm xuất bản:");
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 6, -1, -1));

        NamXBchooser1.setPreferredSize(new java.awt.Dimension(181, 33));
        jPanel14.add(NamXBchooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 28, -1, -1));

        jLabel22.setText("Đơn giá bán:");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 73, 95, -1));

        txtDonGia1.setEditable(false);
        txtDonGia1.setEnabled(false);
        txtDonGia1.setPreferredSize(new java.awt.Dimension(181, 33));
        txtDonGia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGia1ActionPerformed(evt);
            }
        });
        jPanel14.add(txtDonGia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 95, -1, -1));

        ThemBtn1.setBackground(new java.awt.Color(0, 201, 167));
        ThemBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ThemBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        ThemBtn1.setText("Thêm");
        ThemBtn1.setPreferredSize(new java.awt.Dimension(111, 33));
        jPanel14.add(ThemBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 28, 112, -1));

        bodyNhapKho1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 954, -1));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sách", "Tác giả", "Thể loại", "Nhà xuất bản", "Năm XB", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setRowHeight(40);
        jScrollPane3.setViewportView(table1);

        bodyNhapKho1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 134, 914, 350));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ThoatBtn.setBackground(new java.awt.Color(0, 201, 167));
        ThoatBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThoatBtn.setText("Thoát");
        ThoatBtn.setPreferredSize(new java.awt.Dimension(116, 35));
        ThoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatBtnActionPerformed(evt);
            }
        });
        jPanel15.add(ThoatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 6, -1, -1));

        LuuBtn.setBackground(new java.awt.Color(0, 201, 167));
        LuuBtn.setForeground(new java.awt.Color(255, 255, 255));
        LuuBtn.setText("Lưu");
        LuuBtn.setPreferredSize(new java.awt.Dimension(116, 35));
        jPanel15.add(LuuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 6, -1, -1));

        bodyNhapKho1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 490, 942, -1));

        mainThemSach.add(bodyNhapKho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, -1, -1));

        ThemSach.getContentPane().add(mainThemSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CapNhatSach.setBackground(new java.awt.Color(255, 255, 255));
        CapNhatSach.setMinimumSize(new java.awt.Dimension(830, 400));
        CapNhatSach.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header3.setBackground(new java.awt.Color(132, 94, 194));
        header3.setPreferredSize(new java.awt.Dimension(954, 30));
        header3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CẬP NHẬT SÁCH");
        header3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 208, -1));

        CapNhatSach.getContentPane().add(header3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 811, 33));

        SuaDonGiatxt.setEnabled(false);
        SuaDonGiatxt.setPreferredSize(new java.awt.Dimension(370, 36));
        SuaDonGiatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaDonGiatxtActionPerformed(evt);
            }
        });
        CapNhatSach.getContentPane().add(SuaDonGiatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 205, -1, -1));

        jLabel24.setForeground(new java.awt.Color(111, 121, 121));
        jLabel24.setText("Tên đầu sách:");
        CapNhatSach.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 43, 100, -1));

        jLabel25.setForeground(new java.awt.Color(111, 121, 121));
        jLabel25.setText("Tác giả:");
        CapNhatSach.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 43, 79, -1));

        SuaNXBCmb.setPreferredSize(new java.awt.Dimension(370, 36));
        SuaNXBCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaNXBCmbActionPerformed(evt);
            }
        });
        CapNhatSach.getContentPane().add(SuaNXBCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 130, -1, -1));

        SuaThoatBtn.setBackground(new java.awt.Color(0, 201, 167));
        SuaThoatBtn.setForeground(new java.awt.Color(255, 255, 255));
        SuaThoatBtn.setText("Thoát");
        SuaThoatBtn.setPreferredSize(new java.awt.Dimension(69, 34));
        SuaThoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaThoatBtnActionPerformed(evt);
            }
        });
        CapNhatSach.getContentPane().add(SuaThoatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 80, -1));

        SuaLuuBtn.setBackground(new java.awt.Color(0, 201, 167));
        SuaLuuBtn.setForeground(new java.awt.Color(255, 255, 255));
        SuaLuuBtn.setText("Lưu");
        SuaLuuBtn.setPreferredSize(new java.awt.Dimension(69, 34));
        SuaLuuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaLuuBtnActionPerformed(evt);
            }
        });
        CapNhatSach.getContentPane().add(SuaLuuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 80, -1));

        jLabel26.setForeground(new java.awt.Color(111, 121, 121));
        jLabel26.setText("NXB:");
        CapNhatSach.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 110, 83, 20));

        jLabel27.setForeground(new java.awt.Color(111, 121, 121));
        jLabel27.setText("Năm xuất bản:");
        CapNhatSach.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 183, 120, -1));

        SuaNamXBChooser.setPreferredSize(new java.awt.Dimension(370, 36));
        CapNhatSach.getContentPane().add(SuaNamXBChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 205, -1, -1));

        SuaTenDauSachCmb.setPreferredSize(new java.awt.Dimension(370, 36));
        CapNhatSach.getContentPane().add(SuaTenDauSachCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 65, -1, -1));

        jLabel28.setForeground(new java.awt.Color(111, 121, 121));
        jLabel28.setText("Số lượng:");
        CapNhatSach.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 110, 83, -1));

        jLabel29.setForeground(new java.awt.Color(111, 121, 121));
        jLabel29.setText("Đơn giá:");
        CapNhatSach.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 183, 83, -1));

        SuaTacGiaCmb.setEditable(false);
        SuaTacGiaCmb.setEnabled(false);
        SuaTacGiaCmb.setPreferredSize(new java.awt.Dimension(370, 36));
        SuaTacGiaCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaTacGiaCmbActionPerformed(evt);
            }
        });
        CapNhatSach.getContentPane().add(SuaTacGiaCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 65, -1, -1));
        CapNhatSach.getContentPane().add(fileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 311, 37, -1));

        SuaSoLuongtxt.setEditable(false);
        SuaSoLuongtxt.setEnabled(false);
        SuaSoLuongtxt.setPreferredSize(new java.awt.Dimension(370, 36));
        SuaSoLuongtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaSoLuongtxtActionPerformed(evt);
            }
        });
        CapNhatSach.getContentPane().add(SuaSoLuongtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 130, -1, -1));

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        function.setBackground(new java.awt.Color(255, 255, 255));
        function.setPreferredSize(new java.awt.Dimension(996, 44));
        function.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimKiem.setBackground(new java.awt.Color(251, 234, 255));
        TimKiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        TimKiem.setPreferredSize(new java.awt.Dimension(64, 19));
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });
        function.add(TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 230, 30));

        TongSach.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TongSach.setText("Tìm kiếm");
        function.add(TongSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 70, -1));

        ThemSachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addition.png"))); // NOI18N
        ThemSachBtn.setBorder(null);
        ThemSachBtn.setContentAreaFilled(false);
        ThemSachBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemSachBtn.setPreferredSize(new java.awt.Dimension(103, 43));
        ThemSachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemSachBtnActionPerformed(evt);
            }
        });
        function.add(ThemSachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 30, 30));

        NhapKhoBtn.setBackground(new java.awt.Color(0, 201, 167));
        NhapKhoBtn.setForeground(new java.awt.Color(255, 255, 255));
        NhapKhoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhapkho.png"))); // NOI18N
        NhapKhoBtn.setBorder(null);
        NhapKhoBtn.setPreferredSize(new java.awt.Dimension(112, 43));
        NhapKhoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapKhoBtnActionPerformed(evt);
            }
        });
        function.add(NhapKhoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 30, 30));

        lblTongSach.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblTongSach.setForeground(new java.awt.Color(0, 201, 167));
        lblTongSach.setText("2304");
        function.add(lblTongSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 37, -1));

        XoaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        XoaBtn.setBorder(null);
        XoaBtn.setContentAreaFilled(false);
        XoaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });
        function.add(XoaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 12, -1, -1));

        EditBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pen.jpg"))); // NOI18N
        EditBtn.setBorder(null);
        EditBtn.setContentAreaFilled(false);
        EditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        function.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 12, -1, -1));

        TongSach1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TongSach1.setForeground(new java.awt.Color(0, 201, 167));
        TongSach1.setText("Tổng sách: ");
        function.add(TongSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(132, 94, 194));
        jLabel3.setText("SẢN PHẨM");
        function.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        add(function, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 50));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        SachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tác giả", "Tên sách", "NXB", "Năm XB", "Đơn giá", "Tồn kho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SachTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SachTable.setRowHeight(44);
        SachTable.setShowGrid(false);
        SachTable.setUpdateSelectionOnSort(false);
        jScrollPane4.setViewportView(SachTable);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1030, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiemActionPerformed

    private void ThemSachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemSachBtnActionPerformed

        ThemSach.setVisible(true);
    }//GEN-LAST:event_ThemSachBtnActionPerformed

    private void NhapKhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapKhoBtnActionPerformed
        NhapKho.setVisible(true);
    }//GEN-LAST:event_NhapKhoBtnActionPerformed

    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
   //     CapNhatSach.setVisible(true);
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void DauSachCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DauSachCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DauSachCmbActionPerformed

    private void NhaXuatBanCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhaXuatBanCmbActionPerformed

    }//GEN-LAST:event_NhaXuatBanCmbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ThemSach.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed

    }//GEN-LAST:event_ThemBtnActionPerformed

    private void ThoatNhapKhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatNhapKhoBtnActionPerformed
        NhapKho.setVisible(false);
    }//GEN-LAST:event_ThoatNhapKhoBtnActionPerformed

    private void DauSachCmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DauSachCmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DauSachCmb1ActionPerformed

    private void NhaXuatBanCmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhaXuatBanCmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhaXuatBanCmb1ActionPerformed

    private void txtDonGia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGia1ActionPerformed

    private void ThoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatBtnActionPerformed
        ThemSach.setVisible(false);
    }//GEN-LAST:event_ThoatBtnActionPerformed

    private void SuaDonGiatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaDonGiatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuaDonGiatxtActionPerformed

    private void SuaThoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaThoatBtnActionPerformed
        CapNhatSach.setVisible(false);
    }//GEN-LAST:event_SuaThoatBtnActionPerformed

    private void SuaLuuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaLuuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuaLuuBtnActionPerformed

    private void SuaTacGiaCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaTacGiaCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuaTacGiaCmbActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        
    }//GEN-LAST:event_EditBtnActionPerformed

    private void SuaNXBCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaNXBCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuaNXBCmbActionPerformed

    private void SuaSoLuongtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaSoLuongtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuaSoLuongtxtActionPerformed



    public JDialog getCapNhatSach() {
        return CapNhatSach;
    }

    public void setCapNhatSach(JDialog CapNhatSach) {
        this.CapNhatSach = CapNhatSach;
    }

    public JComboBox<String> getDauSachCmb() {
        return DauSachCmb;
    }

    public void setDauSachCmb(JComboBox<String> DauSachCmb) {
        this.DauSachCmb = DauSachCmb;
    }

    public JComboBox<String> getDauSachCmb1() {
        return DauSachCmb1;
    }

    public void setDauSachCmb1(JComboBox<String> DauSachCmb1) {
        this.DauSachCmb1 = DauSachCmb1;
    }

    public JButton getEditBtn() {
        return EditBtn;
    }

    public void setEditBtn(JButton EditBtn) {
        this.EditBtn = EditBtn;
    }



    public JButton getLuuBtn() {
        return LuuBtn;
    }

    public void setLuuBtn(JButton LuuBtn) {
        this.LuuBtn = LuuBtn;
    }

    public JYearChooser getNamXBchooser() {
        return NamXBchooser;
    }

    public void setNamXBchooser(JYearChooser NamXBchooser) {
        this.NamXBchooser = NamXBchooser;
    }

    public JYearChooser getNamXBchooser1() {
        return NamXBchooser1;
    }

    public void setNamXBchooser1(JYearChooser NamXBchooser1) {
        this.NamXBchooser1 = NamXBchooser1;
    }

    public JDateChooser getNgayNhapChooser() {
        return NgayNhapChooser;
    }

    public void setNgayNhapChooser(JDateChooser NgayNhapChooser) {
        this.NgayNhapChooser = NgayNhapChooser;
    }

    public JComboBox<String> getNhaXuatBanCmb() {
        return NhaXuatBanCmb;
    }

    public void setNhaXuatBanCmb(JComboBox<String> NhaXuatBanCmb) {
        this.NhaXuatBanCmb = NhaXuatBanCmb;
    }

    public JComboBox<String> getNhaXuatBanCmb1() {
        return NhaXuatBanCmb1;
    }

    public void setNhaXuatBanCmb1(JComboBox<String> NhaXuatBanCmb1) {
        this.NhaXuatBanCmb1 = NhaXuatBanCmb1;
    }

    public JDialog getNhapKho() {
        return NhapKho;
    }

    public void setNhapKho(JDialog NhapKho) {
        this.NhapKho = NhapKho;
    }

    public JButton getNhapKhoBtn() {
        return NhapKhoBtn;
    }

    public void setNhapKhoBtn(JButton NhapKhoBtn) {
        this.NhapKhoBtn = NhapKhoBtn;
    }

    public JTable getSachTable() {
        return SachTable;
    }

    public void setSachTable(JTable SachTable) {
        this.SachTable = SachTable;
    }

    public JTextField getSuaDonGiatxt() {
        return SuaDonGiatxt;
    }

    public void setSuaDonGiatxt(JTextField SuaDonGiatxt) {
        this.SuaDonGiatxt = SuaDonGiatxt;
    }

    public JButton getSuaLuuBtn() {
        return SuaLuuBtn;
    }

    public void setSuaLuuBtn(JButton SuaLuuBtn) {
        this.SuaLuuBtn = SuaLuuBtn;
    }

    public JComboBox<String> getSuaNXBCmb() {
        return SuaNXBCmb;
    }

    public void setSuaNXBCmb(JComboBox<String> SuaNXBCmb) {
        this.SuaNXBCmb = SuaNXBCmb;
    }

    public JYearChooser getSuaNamXBChooser() {
        return SuaNamXBChooser;
    }

    public void setSuaNamXBChooser(JYearChooser SuaNamXBChooser) {
        this.SuaNamXBChooser = SuaNamXBChooser;
    }

    public JTextField getSuaSoLuongtxt() {
        return SuaSoLuongtxt;
    }

    public void setSuaSoLuongtxt(JTextField SuaSoLuongtxt) {
        this.SuaSoLuongtxt = SuaSoLuongtxt;
    }

    public JTextField getSuaTacGiaCmb() {
        return SuaTacGiaCmb;
    }

    public void setSuaTacGiaCmb(JTextField SuaTacGiaCmb) {
        this.SuaTacGiaCmb = SuaTacGiaCmb;
    }

    public JComboBox<String> getSuaTenDauSachCmb() {
        return SuaTenDauSachCmb;
    }

    public void setSuaTenDauSachCmb(JComboBox<String> SuaTenDauSachCmb) {
        this.SuaTenDauSachCmb = SuaTenDauSachCmb;
    }

    public JButton getSuaThoatBtn() {
        return SuaThoatBtn;
    }

    public void setSuaThoatBtn(JButton SuaThoatBtn) {
        this.SuaThoatBtn = SuaThoatBtn;
    }

    public JButton getThemBtn() {
        return ThemBtn;
    }

    public void setThemBtn(JButton ThemBtn) {
        this.ThemBtn = ThemBtn;
    }

    public JButton getThemBtn1() {
        return ThemBtn1;
    }

    public void setThemBtn1(JButton ThemBtn1) {
        this.ThemBtn1 = ThemBtn1;
    }

    public JDialog getThemSach() {
        return ThemSach;
    }

    public void setThemSach(JDialog ThemSach) {
        this.ThemSach = ThemSach;
    }

    public JButton getThemSachBtn() {
        return ThemSachBtn;
    }

    public void setThemSachBtn(JButton ThemSachBtn) {
        this.ThemSachBtn = ThemSachBtn;
    }

    public JButton getThoatBtn() {
        return ThoatBtn;
    }

    public void setThoatBtn(JButton ThoatBtn) {
        this.ThoatBtn = ThoatBtn;
    }

    public JTextField getTimKiem() {
        return TimKiem;
    }

    public void setTimKiem(JTextField TimKiem) {
        this.TimKiem = TimKiem;
    }

    public JLabel getTongSach() {
        return TongSach;
    }

    public void setTongSach(JLabel TongSach) {
        this.TongSach = TongSach;
    }

    public JLabel getTongSach1() {
        return TongSach1;
    }

    public void setTongSach1(JLabel TongSach1) {
        this.TongSach1 = TongSach1;
    }

    public JButton getXoaBtn() {
        return XoaBtn;
    }

    public void setXoaBtn(JButton XoaBtn) {
        this.XoaBtn = XoaBtn;
    }


    public JPanel getBodyNhapKho() {
        return bodyNhapKho;
    }

    public void setBodyNhapKho(JPanel bodyNhapKho) {
        this.bodyNhapKho = bodyNhapKho;
    }

    public JPanel getBodyNhapKho1() {
        return bodyNhapKho1;
    }

    public void setBodyNhapKho1(JPanel bodyNhapKho1) {
        this.bodyNhapKho1 = bodyNhapKho1;
    }

    public JLabel getFileLabel() {
        return fileLabel;
    }

    public void setFileLabel(JLabel fileLabel) {
        this.fileLabel = fileLabel;
    }

    public JPanel getFunction() {
        return function;
    }

    public void setFunction(JPanel function) {
        this.function = function;
    }

    public JPanel getHeader1() {
        return header1;
    }

    public void setHeader1(JPanel header1) {
        this.header1 = header1;
    }

    public JPanel getHeader2() {
        return header2;
    }

    public void setHeader2(JPanel header2) {
        this.header2 = header2;
    }

    public JPanel getHeader3() {
        return header3;
    }

    public void setHeader3(JPanel header3) {
        this.header3 = header3;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JButton getThoatNhapKhoBtn() {
        return ThoatNhapKhoBtn;
    }

    public void setThoatNhapKhoBtn(JButton ThoatNhapKhoBtn) {
        this.ThoatNhapKhoBtn = ThoatNhapKhoBtn;
    }

    public JButton getNhapSachBtn() {
        return NhapSachBtn;
    }

    public void setNhapSachBtn(JButton NhapSachBtn) {
        this.NhapSachBtn = NhapSachBtn;
    }

    public JLabel getlblTongSach() {
        return lblTongSach;
    }

    public void setlblTongSach(JLabel lblTongSach) {
        this.lblTongSach = lblTongSach;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public void setjLabel26(JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }

    public JLabel getjLabel27() {
        return jLabel27;
    }

    public void setjLabel27(JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    public JLabel getjLabel28() {
        return jLabel28;
    }

    public void setjLabel28(JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    public JLabel getjLabel29() {
        return jLabel29;
    }

    public void setjLabel29(JLabel jLabel29) {
        this.jLabel29 = jLabel29;
    }


    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel12() {
        return jPanel12;
    }

    public void setjPanel12(JPanel jPanel12) {
        this.jPanel12 = jPanel12;
    }

    public JPanel getjPanel13() {
        return jPanel13;
    }

    public void setjPanel13(JPanel jPanel13) {
        this.jPanel13 = jPanel13;
    }

    public JPanel getjPanel14() {
        return jPanel14;
    }

    public void setjPanel14(JPanel jPanel14) {
        this.jPanel14 = jPanel14;
    }

    public JPanel getjPanel15() {
        return jPanel15;
    }

    public void setjPanel15(JPanel jPanel15) {
        this.jPanel15 = jPanel15;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JPanel getMainNhapKho() {
        return mainNhapKho;
    }

    public void setMainNhapKho(JPanel mainNhapKho) {
        this.mainNhapKho = mainNhapKho;
    }

    public JPanel getMainThemSach() {
        return mainThemSach;
    }

    public void setMainThemSach(JPanel mainThemSach) {
        this.mainThemSach = mainThemSach;
    }

    public JTable getNhapTable() {
        return NhapTable;
    }

    public void setNhapTable(JTable NhapTable) {
        this.NhapTable = NhapTable;
    }

    public JTable getTable1() {
        return table1;
    }

    public void setTable1(JTable table1) {
        this.table1 = table1;
    }

    public JTextField getTxtDonGia() {
        return txtDonGia;
    }

    public void setTxtDonGia(JTextField txtDonGia) {
        this.txtDonGia = txtDonGia;
    }

    public JTextField getTxtDonGia1() {
        return txtDonGia1;
    }

    public void setTxtDonGia1(JTextField txtDonGia1) {
        this.txtDonGia1 = txtDonGia1;
    }

    public JTextField getTxtSoLuong() {
        return txtSoLuong;
    }

    public void setTxtSoLuong(JTextField txtSoLuong) {
        this.txtSoLuong = txtSoLuong;
    }

   

    
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CapNhatSach;
    private javax.swing.JComboBox<String> DauSachCmb;
    private javax.swing.JComboBox<String> DauSachCmb1;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton LuuBtn;
    private com.toedter.calendar.JYearChooser NamXBchooser;
    private com.toedter.calendar.JYearChooser NamXBchooser1;
    private com.toedter.calendar.JDateChooser NgayNhapChooser;
    private javax.swing.JComboBox<String> NhaXuatBanCmb;
    private javax.swing.JComboBox<String> NhaXuatBanCmb1;
    private javax.swing.JDialog NhapKho;
    private javax.swing.JButton NhapKhoBtn;
    private javax.swing.JButton NhapSachBtn;
    private javax.swing.JTable NhapTable;
    private javax.swing.JTable SachTable;
    private javax.swing.JTextField SuaDonGiatxt;
    private javax.swing.JButton SuaLuuBtn;
    private javax.swing.JComboBox<String> SuaNXBCmb;
    private com.toedter.calendar.JYearChooser SuaNamXBChooser;
    private javax.swing.JTextField SuaSoLuongtxt;
    private javax.swing.JTextField SuaTacGiaCmb;
    private javax.swing.JComboBox<String> SuaTenDauSachCmb;
    private javax.swing.JButton SuaThoatBtn;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JButton ThemBtn1;
    private javax.swing.JDialog ThemSach;
    private javax.swing.JButton ThemSachBtn;
    private javax.swing.JButton ThoatBtn;
    private javax.swing.JButton ThoatNhapKhoBtn;
    private javax.swing.JTextField TimKiem;
    private javax.swing.JLabel TongSach;
    private javax.swing.JLabel TongSach1;
    private javax.swing.JButton XoaBtn;
    private javax.swing.JPanel bodyNhapKho;
    private javax.swing.JPanel bodyNhapKho1;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JPanel function;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header2;
    private javax.swing.JPanel header3;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTongSach;
    private javax.swing.JPanel mainNhapKho;
    private javax.swing.JPanel mainThemSach;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonGia1;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
