/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlinhasach.view;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author HOANG
 */
public class ThongKe extends javax.swing.JPanel {

   /**
     * Creates new form ThongKe
     */
    Color DefaultColor, ClickedColor, ClickedTextColor, DefaultTextColor;

    
    public ThongKe() {
        initComponents();
        DefaultColor = new Color(247,247,247);
        ClickedColor = new Color(132,94,194);
        DefaultTextColor = new Color(132, 94, 194);
        ClickedTextColor = Color.WHITE;
        jPanelmenu.setBackground(DefaultColor);
        jButton6.setBackground(ClickedColor);
        jButton6.setForeground(ClickedTextColor);
        jButton7.setBackground(DefaultColor);
        showPanel(new CongNo());  // Show default panel when starting
    }

    private void showPanel(JPanel panel) {
        jPanel1.removeAll();
        jPanel1.add(panel).setVisible(true);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void updateButtonBackground(javax.swing.JButton activeButton) {
        jButton6.setBackground(DefaultColor);
        jButton7.setBackground(DefaultColor);
        jButton6.setForeground(DefaultTextColor);
        jButton7.setForeground(DefaultTextColor);
        activeButton.setForeground(ClickedTextColor);
        activeButton.setBackground(ClickedColor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelmenu = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1080, 730));
        setMinimumSize(new java.awt.Dimension(1080, 730));
        setPreferredSize(new java.awt.Dimension(1080, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelmenu.setBackground(new java.awt.Color(247, 247, 247));
        jPanelmenu.setMaximumSize(new java.awt.Dimension(220, 730));
        jPanelmenu.setMinimumSize(new java.awt.Dimension(220, 730));
        jPanelmenu.setName(""); // NOI18N
        jPanelmenu.setPreferredSize(new java.awt.Dimension(220, 730));
        jPanelmenu.setVerifyInputWhenFocusTarget(false);
        jPanelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(247, 247, 247));
        jButton6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(132, 94, 194));
        jButton6.setText("Công nợ");
        jButton6.setBorder(null);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.setMaximumSize(new java.awt.Dimension(200, 36));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 36));
        jButton6.setName(""); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(200, 36));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jPanelmenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton7.setBackground(new java.awt.Color(247, 247, 247));
        jButton7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(132, 94, 194));
        jButton7.setText("Tồn kho");
        jButton7.setBorder(null);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.setMaximumSize(new java.awt.Dimension(200, 36));
        jButton7.setMinimumSize(new java.awt.Dimension(200, 36));
        jButton7.setName(""); // NOI18N
        jButton7.setPreferredSize(new java.awt.Dimension(200, 36));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jPanelmenu.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(132, 94, 194));
        jLabel3.setText("THỐNG KÊ");
        jPanelmenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, -1));

        add(jPanelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setMaximumSize(new java.awt.Dimension(860, 730));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 730));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 730));
        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        showPanel(new CongNo());
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        // TODO add your handling code here:
        updateButtonBackground(jButton6);
        showPanel(new CongNo());
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        showPanel(new TonKho());
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:
        updateButtonBackground(jButton7);
        showPanel(new TonKho());
    }//GEN-LAST:event_jButton7MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelmenu;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }
}
