/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlinhasach.view;

/**
 *
 * @author HOANG
 */
public class ThongKeForm extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeForm
     */
    public ThongKeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelheader = new javax.swing.JPanel();
        jPanelmenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanelsearch = new javax.swing.JPanel();
        jTextFieldsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonsearch = new javax.swing.JButton();
        jButtonimport = new javax.swing.JButton();
        jButtondownload = new javax.swing.JButton();
        jPanelbody = new javax.swing.JPanel();
        jPanelborder = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 768));
        setResizable(false);

        jPanelheader.setBackground(new java.awt.Color(132, 94, 194));
        jPanelheader.setMinimumSize(new java.awt.Dimension(1080, 45));
        jPanelheader.setPreferredSize(new java.awt.Dimension(1080, 45));

        javax.swing.GroupLayout jPanelheaderLayout = new javax.swing.GroupLayout(jPanelheader);
        jPanelheader.setLayout(jPanelheaderLayout);
        jPanelheaderLayout.setHorizontalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1460, Short.MAX_VALUE)
        );
        jPanelheaderLayout.setVerticalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanelmenu.setBackground(new java.awt.Color(247, 247, 247));
        jPanelmenu.setMaximumSize(new java.awt.Dimension(31245, 32145));
        jPanelmenu.setMinimumSize(new java.awt.Dimension(220, 723));
        jPanelmenu.setName(""); // NOI18N
        jPanelmenu.setPreferredSize(new java.awt.Dimension(220, 723));
        jPanelmenu.setVerifyInputWhenFocusTarget(false);

        jButton1.setBackground(new java.awt.Color(132, 94, 194));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lịch sử thu tiền");
        jButton1.setBorder(null);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setMargin(new java.awt.Insets(10, 30, 10, 14));
        jButton1.setName(""); // NOI18N

        jButton2.setBackground(new java.awt.Color(247, 247, 247));
        jButton2.setForeground(new java.awt.Color(132, 94, 194));
        jButton2.setText("Lịch sử bán");
        jButton2.setBorder(null);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setMargin(new java.awt.Insets(10, 30, 10, 14));
        jButton2.setName(""); // NOI18N

        jButton3.setBackground(new java.awt.Color(247, 247, 247));
        jButton3.setForeground(new java.awt.Color(132, 94, 194));
        jButton3.setText("Lịch sử nhập");
        jButton3.setBorder(null);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setMargin(new java.awt.Insets(10, 30, 10, 14));
        jButton3.setName(""); // NOI18N

        jButton4.setBackground(new java.awt.Color(247, 247, 247));
        jButton4.setForeground(new java.awt.Color(132, 94, 194));
        jButton4.setText("Doanh thu");
        jButton4.setBorder(null);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setMargin(new java.awt.Insets(10, 30, 10, 14));
        jButton4.setName(""); // NOI18N

        jButton5.setBackground(new java.awt.Color(247, 247, 247));
        jButton5.setForeground(new java.awt.Color(132, 94, 194));
        jButton5.setText("Sách bán chạy");
        jButton5.setBorder(null);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setMargin(new java.awt.Insets(10, 30, 10, 14));
        jButton5.setName(""); // NOI18N

        jButton6.setBackground(new java.awt.Color(247, 247, 247));
        jButton6.setForeground(new java.awt.Color(132, 94, 194));
        jButton6.setText("Công nợ");
        jButton6.setBorder(null);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setMargin(new java.awt.Insets(10, 30, 10, 14));
        jButton6.setName(""); // NOI18N

        jButton7.setBackground(new java.awt.Color(247, 247, 247));
        jButton7.setForeground(new java.awt.Color(132, 94, 194));
        jButton7.setText("Tồn kho");
        jButton7.setBorder(null);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setMargin(new java.awt.Insets(10, 30, 10, 14));
        jButton7.setName(""); // NOI18N

        javax.swing.GroupLayout jPanelmenuLayout = new javax.swing.GroupLayout(jPanelmenu);
        jPanelmenu.setLayout(jPanelmenuLayout);
        jPanelmenuLayout.setHorizontalGroup(
            jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelmenuLayout.setVerticalGroup(
            jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelsearch.setBackground(new java.awt.Color(255, 255, 255));
        jPanelsearch.setMinimumSize(new java.awt.Dimension(860, 76));
        jPanelsearch.setPreferredSize(new java.awt.Dimension(860, 76));

        jTextFieldsearch.setBackground(new java.awt.Color(251, 234, 255));
        jTextFieldsearch.setForeground(new java.awt.Color(132, 94, 194));
        jTextFieldsearch.setText("Tìm kiếm");
        jTextFieldsearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 94, 194), 2, true));
        jTextFieldsearch.setDisabledTextColor(new java.awt.Color(132, 94, 194));
        jTextFieldsearch.setSelectedTextColor(new java.awt.Color(132, 94, 194));
        jTextFieldsearch.setSelectionColor(new java.awt.Color(251, 234, 255));
        jTextFieldsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsearchActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đến");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Từ");

        jButtonsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/search.png"))); // NOI18N
        jButtonsearch.setBorder(null);

        jButtonimport.setBorder(null);

        jButtondownload.setBorder(null);

        javax.swing.GroupLayout jPanelsearchLayout = new javax.swing.GroupLayout(jPanelsearch);
        jPanelsearch.setLayout(jPanelsearchLayout);
        jPanelsearchLayout.setHorizontalGroup(
            jPanelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsearchLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287)
                .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButtonimport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtondownload, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelsearchLayout.setVerticalGroup(
            jPanelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsearchLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2))
            .addGroup(jPanelsearchLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1))
            .addGroup(jPanelsearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelsearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelsearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonimport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelsearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtondownload, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelbody.setBackground(new java.awt.Color(255, 255, 255));
        jPanelbody.setMinimumSize(new java.awt.Dimension(860, 647));
        jPanelbody.setName(""); // NOI18N
        jPanelbody.setPreferredSize(new java.awt.Dimension(860, 647));

        jPanelborder.setBackground(new java.awt.Color(204, 179, 235));
        jPanelborder.setMinimumSize(new java.awt.Dimension(811, 569));
        jPanelborder.setPreferredSize(new java.awt.Dimension(811, 569));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(771, 529));
        jTable1.setPreferredSize(new java.awt.Dimension(771, 529));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelborderLayout = new javax.swing.GroupLayout(jPanelborder);
        jPanelborder.setLayout(jPanelborderLayout);
        jPanelborderLayout.setHorizontalGroup(
            jPanelborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelborderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelborderLayout.setVerticalGroup(
            jPanelborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelborderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelbodyLayout = new javax.swing.GroupLayout(jPanelbody);
        jPanelbody.setLayout(jPanelbodyLayout);
        jPanelbodyLayout.setHorizontalGroup(
            jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbodyLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelborder, javax.swing.GroupLayout.PREFERRED_SIZE, 1171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelbodyLayout.setVerticalGroup(
            jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbodyLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelborder, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelheader, javax.swing.GroupLayout.PREFERRED_SIZE, 1460, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelbody, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelbody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtondownload;
    private javax.swing.JButton jButtonimport;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelbody;
    private javax.swing.JPanel jPanelborder;
    private javax.swing.JPanel jPanelheader;
    private javax.swing.JPanel jPanelmenu;
    private javax.swing.JPanel jPanelsearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldsearch;
    // End of variables declaration//GEN-END:variables
}
